### ISSUE TITLE
Better name for --parallel?

### ISSUE THREAD

**Issue by NiallRees** [sqlfluff/sqlfluff#1057]
I feel that --threads instead of --parallel is clearer in terms of what the input value does. We can also then change the help string to specify that the number passed is the number of threads used.

**Comment by barrywhart** [comment]
`--threads` was the original suggestion. I used `--parallel` for two main reasons:
* Generally, to avoid incorrect terminology: the implementation uses processes rather than threads. (Python threads do not scale well for this kind of processing due to the [GIL](https://wiki.python.org/moin/GlobalInterpreterLock).)
* The GNU `xargs` command uses [`-P` for parallel processing](https://man7.org/linux/man-pages/man1/xargs.1.html).

Is there another term we may want to consider?

**Comment by NiallRees** [comment]
Maybe `--parallelism`? If it was just a boolean, `--parallel` makes sense, but as it's a configuration parameter less so (to me).

**Comment by barrywhart** [comment]
I'm open to change, but would like input from a few more people to try and have some consensus. @alanmcruickshank @dmateusp @nolanbconaway @pwildenhain 

Like? Dislike? Other suggestions?

**Comment by pwildenhain** [comment]
`processes`
`processors`

Agree that `parallel` sounds like a Boolean.

**Comment by nolanbconaway** [comment]
I personally like `--processes`, but mostly because i have never successfully spelled parallel correctly on my first attempt!

**Comment by NiallRees** [comment]
I like that too!

**Comment by barrywhart** [comment]
Sounds good to me. Let's do this after @alanmcruickshank fixes the dbt parallelism issue. (Boo, merge conflicts!)
