### ISSUE TITLE
Dbt templater re-runs compile for each file while running parallel

### ISSUE THREAD

**Issue by alanmcruickshank** [sqlfluff/sqlfluff#1088]
While debugging slow running using the new `--parallel` feature, I've found that the dbt templater is running the compile step again for each file.

I *think* this is because each file uses it's own `Linter` object and so doesn't utilise the cached methods on the dbt templater.

The solution to this I think is to run the templating step in the main thread before dispatching out for parsing and linting. This should be possible by modifying the runner classes and the method calls available on `Linter`. The tricky part will be splitting out the templating step from `Linter.lint_string()` and `Linter.parse_string()`.

@barrywhart , having thought about this today, I was going to suggest this:
- We *don't* create a new `Linter` for each file.
- Instead, we abstract the parsing and linting methods out into `staticmethods` which can be safely called by the threads. Behind the existing methods of `parse_string()` and `lint_string()` there will be private methods of `_render_string()`, `_parse()` and `_lint()` which are static methods and handle all of the meaningful logic. These can be called via the existing methods _or directly from the runner classes_.
- In the parallel runners, the templating step (`_render_string()`) is called in the main thread, and then the resulting `TemplatedFile` in handed off to a child process to parse and lint (`_parse()` and `_lint()`). Those child processes never need their own `Linter()` object because they're just using the static methods, but might need a copy of the `FluffConfig` or similar objects.

Reckon that could work? I'm happy to have a go at this, I should probably get more familiar with the parallel code as is.

**Comment by barrywhart** [comment]
That sounds like a good plan. I like the design of using static methods in the worker processes because it limits the number of object instances being passed to the workers. With `multiprocessing.Pool`, I've seen things get pretty confusing if you call normal instance methods from the workers, because Python serializes those objects automatically, but of course in the child it's not the same object, etc. etc. Far better to pass entire objects that you deliberately want to pass.

@alanmcruickshank: Go for it! I appreciate the help. Suddenly, work has gotten pretty busy for me with new hires, etc. etc.
