### ISSUE TITLE
Some new test cases

### ISSUE THREAD

**Issue by SpokeyWheeler** [sqlfluff/sqlfluff#1121]
I have been through all the static SQL I can find and I've got ~95 different SQL statements, all anonymised. Obviously, there are variations on a theme, and I fully expect that some of these already have suitable test cases. Some of these will be Cockroach-specific, I've identified my suspicions.

How do I go about getting these test cases in? Should I add them all at once, or drip feed them? I'll need to be reminded where to put them. 😳

**Comment by SpokeyWheeler** [comment]
I would like to add at least some Cockroach-specific dialect. Will SQLFluff check ANSI as well as the dialect? Or do I have to add all ANSI stuff to the Cockroach directory as well?

Also, I presume that the parser won't parse at least some of the SQL I have and it's going to take me (possibly) ages to add it all to SQLFluff. Is it going to be a problem to have failing tests and SQL that doesn't have a YAML?

**Comment by barrywhart** [comment]
Rather than saying:
>Will SQLFluff check ANSI as well as the dialect?

it would be more accurate to say that other dialects inherit from ANSI, then they extend or tweak it. You only have to write code for parts that are new or different from the parent. If you look at the relative size of the various `dialect_*.py` files, you'll see that ANSI is the biggest. Snowflake and BigQuery are the next largest because they have a number of additional features not present in ANSI.

Initially, I suggest creating a basic Cockroach dialect that supports a few of the highest priority Cockroach-specific features and creating a PR for that (including tests). If you have tests that won't pass, you should add those in your own private fork, and gradually add them to the main SQLFluff repo as you get things working.

**Comment by SpokeyWheeler** [comment]
Fab. Unfortunately, I've run into a bug #1129 :-(

**Comment by SpokeyWheeler** [comment]
I'm happy to close this ticket for now, as I have a path forward. Thank you!
