### ISSUE TITLE
SQL JINJA IS EXPLODING with sqlfluff fix

### ISSUE THREAD

**Issue by jonny-mills** [sqlfluff/sqlfluff#1162]
-- If this is a parsing or linting issue, please include a minimal SQL example which reproduces the issue, along with the `sqlfluff parse` output, `sqlfluff lint` output and `sqlfluff fix` output when relevant. Finally, please add any labels that are related to the issue before submitting so that it can be addressed easily! --

SIMPLE SQL QUERY
```
SELECT
    apple
    , {% for num in ('1', '2', '3') %}
            CASE WHEN {{ num }} = 1 THEN cool
            ELSE moo END as {{ num }}_col
      {% endfor -%}
    , pear
from fruit f
```

## Expected Behaviour

```
SELECT
    apple,
    {% for num in ('1', '2', '3') %}
            CASE WHEN {{ num }} = 1 THEN cool
            ELSE moo END as {{ num }}_col
      {% endfor -%}
    pear
FROM fruit
```

## Observed Behaviour
```
SELECT
    apple,
    {% for num in ('1', '2', '3') %}
            CASE WHEN {{ num }} = 1 THEN cool
            ELSE moo END as {{ num }}_col
      {% endfor -%}
    CASE WHEN 1 = 1 THEN cool
            ELSE moo END as 1_col

            CASE WHEN 2 = 1 THEN cool
            ELSE moo END as 2_col

            CASE WHEN 3 = 1 THEN cool
            ELSE moo END as 3_col
FROM fruit
```

## Steps to Reproduce
create a file called test.sql with
```
SELECT
    apple,
    {% for num in ('1', '2', '3') %}
            CASE WHEN {{ num }} = 1 THEN cool
            ELSE moo END as {{ num }}_col
      {% endfor -%}
    pear
FROM fruit

```

## Version
Include the output of `sqlfluff --version` along with your Python version

sqlfluff, version 0.6.0
Python 3.7.9
## Configuration
```
Include your SQLFluff configuration here
```
```
[sqlfluff]
dialect = snowflake
load_macros_from_path = macros

[sqlfluff:rules:L010]
capitalisation_policy = upper

#[sqlfluff:rules:L016]
#max_line_length = 999

[sqlfluff:rules:L019]
comma_style = trailing
```

**Comment by barrywhart** [comment]
@jonny-mills: If you run `sqlfluff lint` on this file, are you seeing a parse error? I'm seeing this (note the parse error on line 3):
```
sqlfluff lint test.sql
== [test.sql] FAIL
L:   3 | P:  37 |  PRS | Line 5, Position 25: Found unparsable section: ' as
                       | 1_col\n \n CASE WHEN 2...'
L:   4 | P:  13 | L003 | Line over-indented compared to line #2
L:   6 | P:   1 | L001 | Unnecessary trailing whitespace.
L:   6 | P:   1 | L001 | Unnecessary trailing whitespace.
L:   8 | P:   1 | L003 | Indentation not consistent with line #2
```

I'm not saying that SQLFluff is behaving correctly, just trying to understand, reproduce, and prioritize issues.

**Comment by barrywhart** [comment]
The parse error appears to be caused by a missing comma at the end of line 5. Suggest testing with this instead:
```
SELECT
    apple,
    {% for num in ('1', '2', '3') %}
            CASE WHEN {{ num }} = 1 THEN cool
            ELSE moo END as {{ num }}_col,
      {% endfor %}
    pear
FROM fruit
```

`sqlfluff fix` still corrupts the output file, although it looks a bit different.
```
SELECT
    apple,
    {% for num in ('1', '2', '3') %}
            CASE WHEN {{ num }} = 1 THEN cool
            ELSE moo END as {{ num }}_col,
{% endfor %}
    CASE WHEN 3 = 1 THEN cool
               ELSE moo END as 3_col
FROM fruit
```

It would be cool if SQLFluff could actually _fix_ the template. At the very least, it should do nothing, rather than corrupt the code inside a Jinja `for` loop. (I bet there are similar issues with Jinja `if` statements.)

**Comment by tunetheweb** [comment]
As I understand it SQLFluff expands templates to get real SQL and then applies fixes and then has to map fixes back to unexpanded, original template. I think that’s very tricky to do with more complex actions like for loops.

**Comment by barrywhart** [comment]
I'm taking a closer look at this issue. I created an updated, more minimal test case. It's very similar to the original and produces the same "loop exploding" behavior but only involves one rule (L016: leading/trailing commas).

Test file:
```
SELECT
    apple,
    {% for num in ('1', '2', '3') %}
        CASE WHEN {{ num }} = 1 THEN cool ELSE moo END as {{ num }}_col
    {% endfor %}
    , pear
FROM fruit
```

`.sqlfluff`:
```
[sqlfluff]
dialect = snowflake
load_macros_from_path = macros
exclude_rules= L016

[sqlfluff:rules:L019]
comma_style = trailing
```

**Comment by barrywhart** [comment]
Besides the obvious issue where the post-templated loop appears in the "fixed" SQL, there's a more subtle but equally bad issue here: Rule L034 ("Use wildcards then simple targets before calculations and aggregates in select statements.") is trying to move "pear" to appear before the `CASE` statement. This involves two changes:

1. Deleting it from its original location
2. Adding it to the new location

SQLFluff does the first but not the second, so it ends up _deleting_ a column from the `SELECT`. 😱 This is just wrong. Not sure how we'll handle this internally, but conceptually, if a single fix touches multiple areas of the code, it should be an "all or nothing" thing in order to avoid issues like this.

**Comment by barrywhart** [comment]
I noticed the original test case has a parse error because the loop is not adding commas between the columns. Was that also  the case with your original (real-world) issue, @jonny-mills? There may be several different issues here, and I want to focus on  the ones that are important to you.

For now, I changed my test case so it avoids the syntax error (by only executing the loop once) but still produces the bad behavior (expanded loop code appearing outside the loop body after fix).

**Comment by barrywhart** [comment]
A thought: Take a closer look at `BaseSegment.iter_patches()`. Perhaps it could be "smarter" about placing patches on the correct source slices. Specifically, the patch with the string "pear" has a `templated_idx` value that places it inside the `CASE` statement, which causes it to be discarded. Could it be mapped to the point just after `apple,\n`? In order for fixes to work well near template blocks (Jinja for, if, etc.), they need to be placed correctly inside or outside of the block, and I'm not sure that's working as well as it could.

**Comment by barrywhart** [comment]
I've found an interesting issue which may be important: after applying lint fixes to the parse tree, the `apple` segment "looks" like newly inserted code, even though it shouldn't have changed AFAICT. This in turn causes the changes to "look" bigger than they are, and that prevents some of them from being applied. Looking into this more closely...

It causes this code in `segments/base.py` to execute for `apple`:
```
                # First check for insertions.
                # We know it's an insertion if it has length but not in the templated file.
                if segment.raw and segment.pos_marker.is_point():
                    # Add it to the insertion buffer if it has length:
                    if segment.raw:
                        insert_buff += segment.raw
                        linter_logger.debug(
                            "Appending insertion buffer. %r @idx: %s",
                            insert_buff,
                            templated_idx,
                        )
                    continue
```

**Comment by barrywhart** [comment]
@jonny-mills: I've found the issue here. It will take some time to fix, but L034 is the culprit. It rearranges the order of columns to place simpler column definitions first. Unfortunately, here that means it moves columns into or out of the loop. The fix will be to make SQLFluff smart enough to ignore fixes that do this, but for now, you can work around this by excluding rule L034 from running.

**Comment by barrywhart** [comment]
@NiallRees, @tunetheweb, @alanmcruickshank: I think L034 is the only rule in SQLFluff that makes "non-local" changes, i.e. rearranging large amounts of code. Hence, it is the only rule that would trigger this issue. Given the complexity of fixing this issue, I wonder if we may want to consider disabling this rule for now.

**Comment by jonny-mills** [comment]
@barrywhart and everyone else involved, thanks so much for looking into this! To answer your question - this particular sql file was trying to create fields that defined open/closed hours for given days of the week.

```
    {%- for day in var("days_of_week_abbr") -%}
            {%- for hour_type in ('open', 'close') -%}
                , a.{{day}}_{{hour_type}}
        {%- endfor -%}
    {%- endfor -%}
```
So you're saying if I disable L034, that would apply a bandaid to this problem?

**Comment by barrywhart** [comment]
Yes, it'll eliminate the issue. You may encounter other issues, but one thing at a time!
