### ISSUE TITLE
"Applying rule L016 threw an Exception: Is this possible?"

### ISSUE THREAD

**Issue by CyberShadow** [sqlfluff/sqlfluff#1456]
## Expected Behaviour

Probably valid SQL should not cause internal exceptions in SQLFluff.

## Observed Behaviour

`sqlfluff fix` prints an exception. However, that does not prevent in from working as a whole, so this does not block general usage.

## Steps to Reproduce

```console
$ echo "{% set elements = 'foo' %}

    SELECT CASE
      {% for elem in elements %}
        WHEN '{{ elem }}' = '' THEN 1
        WHEN '{{ elem }}' = '' THEN 1
      {%endfor %}
      END

" | sqlfluff fix -
CRITICAL   [L016] Applying rule L016 threw an Exception: Is this possible? 
Traceback (most recent call last):
  File "/home/vladimir/work/extern/sqlfluff/src/sqlfluff/core/rules/base.py", line 302, in crawl
    res = self._eval(
  File "/home/vladimir/work/extern/sqlfluff/src/sqlfluff/rules/L016.py", line 511, in _eval
    fixes = self._eval_line_for_breaks(this_line)
  File "/home/vladimir/work/extern/sqlfluff/src/sqlfluff/rules/L016.py", line 266, in _eval_line_for_breaks
    raise ValueError("Is this possible?")  # pragma: no cover
ValueError: Is this possible?
(...repeated 6 times...)
Unfixable violations detected.
```

## Dialect

None specified

## Version
SQLFluff 6011bdbe05669b075045e8127cdf18cc537686d4, Python 3.9.6

## Configuration

None

**Comment by tunetheweb** [comment]
Seems very similar to #1439 that I fixed recently. Will have a look.

**Comment by tunetheweb** [comment]
@barrywhart this is a weird one and something we broke in 0.6.6 (presumably due to #1411).

It calculates the following line lengths:

```
 26:  {% set elements = 'foo' %}
  0: 
 14:     SELECT CASE
 32:      {% for elem in elements %}
 36:        WHEN 'f' = '' THEN 1
126:        WHEN 'f' = '' THEN 1
 83:
 95:        WHEN 'o' = '' THEN 1
126:        WHEN 'o' = '' THEN 1
 83:
 95:        WHEN 'o' = '' THEN 1
 36:        WHEN 'o' = '' THEN 1
 17:      {%endfor %}
```

The line lengths for each of the `WHEN` lines are incorrect, and it appears to be because it's calcing the length as from the end of the templated area back to the beginning, rather than just the line.

I'm kinda getting lost in this code to be honest, but you any ideas from your work on #1411 ?

**Comment by barrywhart** [comment]
I'll try and look tomorrow. I've been in so many unfamiliar areas of the code lately, not much has stuck in my head. 😅

**Comment by barrywhart** [comment]
A simple thought, but I probably assumed (mistakenly) that each template "literal" is a single line (I.e. no embedded newlines). So the fix may be to split the slice's text into lines and compute length based on the relevant line.

**Comment by barrywhart** [comment]
@tunetheweb: Let me know how this goes. The areas of the linter that have to "look back" into the raw (pre-expanded) source code can be pretty tricky. That's where I've been the past few days with the indentation issue (#1436). Often, in order to make progress, I have to create lots of new test cases, ranging from the simple to the complex, in order to build up my "mental muscles" (See L003.yml in my current PR for an example.) Jumping into a difficult case right away is a recipe for headaches and brick walls. 😅 

Is the new behavior bad enough that we should consider rolling back my original PR?

**Comment by tunetheweb** [comment]
OK after days spent on this I finally figured it out and it basically comes down to this:

https://github.com/sqlfluff/sqlfluff/blob/826798198aa663739ad81ce7b1b3e4192b4d4ab9/src/sqlfluff/core/templaters/python.py#L918-L929

Basically, as I understand it, the Jinja APIs don't map templated files back to source for us, so we make a best attempt to do this, by parsing in turn, and matching based on anchor points.

However for `for` loops, and particularly for `for` loops which don't have nice starting anchor points, we basically give up and set any non-unique sections to the whole `for` loop.

Looking at the SQL in question:

```sql
{% set elements = 'foo' %}

    SELECT CASE
      {% for elem in elements %}
        WHEN '{{ elem }}' = '' THEN 1
        WHEN '{{ elem }}' = '' THEN 1
      {%endfor %}
      END
```

the first part of the `for` loop (`\n        WHEN '`) is not unique so get's mapped back to the entire for loop (\n        WHEN ' ... THEN 1 ... \n WHEN ' ... THEN 1\n`).

This makes the line length look a lot larger than it really is, hence fails L016, but also throws this nasty exception as it kind of doesn't expect to get into this situation.

This particular instance can be handled a bit better - since we're setting the start of the `for` loop to the entire `for` loop, we can just match off the first part (e.g. `\n        WHEN '`) and set that reduced amount, then assume the remainder is a templated section.

This fixes this particular use case, and is a good improvement IMHO, however it still won't handle really complex use cases such as:

```sql
{% set elements = 'foo' %}
{% set when = 'WHEN' %}
SELECT
    CASE
        {% for elem in elements %}
        {{ when }} '{{ elem }}' = '' THEN 1
        {{ when }} '{{ elem }}' = '' THEN 1
        {% endfor %}
    END
```

But hey every step, is a step forward and not sure how likely above is.

@CyberShadow on that point, do you have your actual SQL for this, as I'd argue your example is not really SQL that would be used in real life as you have two identical WHEN clauses. This wouldn't have been an issue if they were different. If you can give your actual SQL I can verify the issue is definitely fixed for your SQL.

**Comment by CyberShadow** [comment]
Thanks for looking into this!

I can't post the full real SQL, but here is another reduction which also exhibits the same error, but without the identical WHEN clauses:

```sql
{% set elements = ['a', 'b'] %}

SELECT
    {% for elem in elements %}
        x1_{{ elem }},
    {% endfor %}
    {% for elem in elements %}
        x2_{{ elem }},
    {% endfor %}
```

Hope this helps.

**Comment by tunetheweb** [comment]
Good news - that no longer throws an exception either with the fix in #1494 :
```
L:   4 | P:  31 | L003 | Line over-indented compared to line #3
L:   8 | P:   1 | L039 | Unnecessary whitespace found.
L:   8 | P:  22 | L038 | Trailing comma in select statement forbidden
```

**Comment by CyberShadow** [comment]
Fantastic. I tested it on the full original file and it doesn't happen there either. Thank you!

**Comment by tunetheweb** [comment]
Great stuff! Nice to know all the effort here was worth while - cause it nearly drove me insane figuring it out!! 😁 Even though, as often is the case, the changes themselves are quite small in the end...

**Comment by barrywhart** [comment]
Very nice work, @tunetheweb! Thanks so much, and I understand how you feel. I just spent a week deciphering L003 to fix a bug there. 🙏🏽

**Comment by tunetheweb** [comment]
@CyberShadow I had to go for a simpler fix in the end. Can you re-try your query against #1494 again to make sure it still fixes it?

I checked your other sample query from https://github.com/sqlfluff/sqlfluff/issues/1456#issuecomment-932901459 and it still lints now so hoping your one is the same.

**Comment by CyberShadow** [comment]
> Can you re-try your query against #1494 again to make sure it still fixes it?

Yes, it is still fixed :)

Also, I just noticed that the old version of #1494 produced corrupt code, but the latest one doesn't.

**Comment by tunetheweb** [comment]
Ah well. Simplicity rules. Though annoying as though we'd make some good progress on fixing Jinja For Loops with the original version :-(
