### ISSUE TITLE
Parser should handle newline-concatenated string literals in more situations

### ISSUE THREAD

**Issue by leamingrad** [sqlfluff/sqlfluff#1488]
## Expected Behaviour

The following should parse successfully:

```sql
SELECT * FROM t_table WHERE c_column = 'foo'
'bar';

SELECT * FROM t_table WHERE c_column IN (
    'FOO'
    'BAR',
    'BAZ'
);

SELECT 'foo'
'bar'
'baz';
```

## Observed Behaviour

`sqlflull parse` fails with the following violations (full output attached):

```
==== parsing violations ====
L:   1 | P:  45 |  PRS | Line 1, Position 45: Found unparsable section: "\n'bar'"
L:   5 | P:   5 |  PRS | Line 5, Position 5: Found unparsable section: "'FOO'\n 'BAR',\n
                       | 'BAZ'"
L:  11 | P:   6 |  PRS | Line 11, Position 6: Found unparsable section: "\n'baz'"
```

[error_output.txt](https://github.com/sqlfluff/sqlfluff/files/7268779/error_output.txt)

## Dialect

This appears to currently happen in every dialect. In section 4.1.2.1 of the [Postgres docs](https://www.postgresql.org/docs/11/sql-syntax-lexical.html), it says:

> Two string constants that are only separated by whitespace with at least one newline are concatenated and effectively treated as if the string had been written as one constant.
> ...
>  (This slightly bizarre behavior is specified by SQL; PostgreSQL is following the standard.)

which makes me think this should be handled by the `ansi` dialect. I haven't been able to test with any other databases, but PostgreSQL will parse all of the example SQL (even the one with three contatenated strings).

## Version
Taken from latest `main` (0.6.6) on Python 3.8.3

**Comment by jpy-git** [comment]
So this also affects MySQL, although in mysql it's space or newline separated. Postgres is newline separated only. (I've also checked and verified that Snowflake doesn't allow these space/newline separate string literals)

![image](https://user-images.githubusercontent.com/80432516/150139967-ad418fb3-4161-41dd-8250-399ddf5ac29e.png)

One thing we'll also need to clear up for these dialects first is that the current ANSI alias definition allows string literals as an alias (since this is possible in T-SQL and bigquery). So those examples I've shown above are parsing in sqlfluff as a string literal `abc` aliased as a column `def` rather than the string literal `abcdef`. So will need to fix the alias definition first and then look at parsing these multiline string literals.

**Comment by jpy-git** [comment]
An additional refinement is that comments can be placed between the concatenated literals so this will have to be handled via grammar rather than a lexer:
![image](https://user-images.githubusercontent.com/80432516/150159696-e110456c-eff4-477e-8980-0333181caedf.png)

**Comment by jpy-git** [comment]
@rpr-ableton Would you be able to do me a quick favour since you have access to redshift?

I've got a fix for postgres and mysql but want to confirm the extent to which redshift supports this, given that it inherits from postgres. Would you be able to run each of these queries and let me know if they're valid in redshift please? 😄 
```sql
SELECT '';

SELECT '''';

SELECT '

';

SELECT '''aaa''';

SELECT '
''
';

SELECT 'foo'
'bar';

SELECT 'foo'


'bar';

SELECT 'foo' -- some comment
'bar';
```

Maybe also try
```sql
SELECT 'foo'   'bar'
```
which isn't valid syntax in postgres but is in mysql, just in case redshift is doing anything extra

**Comment by rpr-ableton** [comment]
@jpy-git sure thing! All the statements in your first code block are valid in Redshift.

However `SELECT 'foo'   'bar'` isn't :smile:

**Comment by jpy-git** [comment]
Amazing, thanks mate! 😊
