### ISSUE TITLE
Add support for .sqlx files (Dataform)

### ISSUE THREAD

**Issue by rubenlopezlozoya** [sqlfluff/sqlfluff#1540]
Given the rising popularity of Dataform I believe it would be great to add linting capabilities for .sqlx files!

**Comment by barrywhart** [comment]
Update to my above comment: I left my previous job, where they were using Dataform. Because of Dataform being written in a different language, this seems like quite a significant project, and I'm not going to be taking it on.

Any volunteers?

**Comment by bruno-nirello** [comment]
up

**Comment by barrywhart** [comment]
This is very unlikely to happen unless someone with TypeScript experience steps up. None of the current maintainers use it.

Google bought the company and now it's a proprietary product. Has anyone tried pushing their Google reps to get them to work on it?

**Comment by astorrs** [comment]
I dropped a note to the Dataform PM.

**Comment by timbusfield** [comment]
To try and break the problem down, would it just be a case of?...
1. Identifying which sections of the files are JS blocks and which are BQ SQL statements
2. Apply some JS linting to the JS blocks (new functionality) and BQ linting to the BQ SQL statements (existing functionality)
3. Recombine the linted sections

**Comment by timbusfield** [comment]
Excuse the scratchy code, this doesn't cover all of the idiosyncrasies of SQLX but focuses on the two main ones; the config block and ${ref...} function

`python
my_query = """config {
  type: "table",
  schema: "my schema",
  description: "example sqlx"
}

--Comment line
SELECT thing FroM           ${  ref("orders")}  GROUP           BY ${ref("segment")}"""

# Find the config block (if one exists), split the text into a config
# block section that isn't linted and the remaining text that will be
config_block_string = re.search("config\s+\{((.|\n)*?)\}", my_query)[0]
remaining_text = my_query.replace(config_block_string, "")

# Identify each builtin function reference and replace it with a temporary mask
# in order to pass the text through the  
built_ins = re.findall("\$\{(.*?)\}", remaining_text)

mask = list()
for match in built_ins:
    # hacky way to generate a unique string that meets the BQ rules 
    mask_string = "a" + str(uuid.uuid1()).replace("-", ".a")
    remaining_text = remaining_text.replace("${" + match + "}", mask_string)
    mask.append((mask_string, "${" + match.strip() + "}"))

# run fix on modified text
bq_fix_result = sqlfluff.fix(remaining_text, dialect="bigquery")

# place the builtins back into the SQL(X)
for m in mask:
    bq_fix_result = bq_fix_result.replace(m[0], m[1])

# recombine the config block and the fixed SQL
combined_fix = config_block_string + "\n\n" + bq_fix_result

print(combined_fix)
# config {
#   type: "table",
#   schema: "my schema",
#   description: "example sqlx"
# }

# --Comment line
# SELECT thing
# FROM
#     ${ref("orders")}
# GROUP BY ${ref("segment")}`

**Comment by timbusfield** [comment]
Excuse the scratchy code, this doesn't cover all of the idiosyncrasies of SQLX but focuses on the two main ones; the config block and ${ref...} function

```python
my_query = """config {
  type: "table",
  schema: "my schema",
  description: "example sqlx"
}

--Comment line
SELECT thing FroM           ${  ref("orders")}  GROUP           BY ${ref("segment")}"""

# Find the config block (if one exists), split the text into a config
# block section that isn't linted and the remaining text that will be
config_block_string = re.search("config\s+\{((.|\n)*?)\}", my_query)[0]
remaining_text = my_query.replace(config_block_string, "")

# Identify each builtin function reference and replace it with a temporary mask
# in order to pass the text through the  
built_ins = re.findall("\$\{(.*?)\}", remaining_text)

mask = list()
for match in built_ins:
    # hacky way to generate a unique string that meets the BQ rules 
    mask_string = "a" + str(uuid.uuid1()).replace("-", ".a")
    remaining_text = remaining_text.replace("${" + match + "}", mask_string)
    mask.append((mask_string, "${" + match.strip() + "}"))

# run fix on modified text
bq_fix_result = sqlfluff.fix(remaining_text, dialect="bigquery")

# place the builtins back into the SQL(X)
for m in mask:
    bq_fix_result = bq_fix_result.replace(m[0], m[1])

# recombine the config block and the fixed SQL
combined_fix = config_block_string + "\n\n" + bq_fix_result

print(combined_fix)
# config {
#   type: "table",
#   schema: "my schema",
#   description: "example sqlx"
# }

# --Comment line
# SELECT thing
# FROM
#     ${ref("orders")}
# GROUP BY ${ref("segment")}
```

**Comment by barrywhart** [comment]
Does DataForm templating support things like `if` statements, loops, and macros? If so, handling that is trickier than simply splitting the file, you have to actually run the templating to know what parts are included in the output file and where. And when there's substitution, you have to know **what** is being substituted -- it could be anything: column name, an entire `WHERE` clause, arbitrary bits of SQL, etc. This [module](https://github.com/sqlfluff/sqlfluff/blob/main/src/sqlfluff/core/templaters/slicers/tracer.py) is how we do it for Jinja and dbt.

**Comment by HGourier** [comment]
Hello everybody, 
@barrywhart , Dataform supports anything available in Google standard SQL, including if statements and loops. It is also possible to define macros and functions using javascript that are then parsed into the SQL that gets compiled (please see this [link](https://docs.dataform.co/guides/javascript) for more information). 
Is anybody working on developing this tool? @astorrs, Did you get a response from Google? 
I believe it would make the task a lot easier if we could get access to the compiled files through an api?

**Comment by barrywhart** [comment]
Access to the compiled code is unfortunately not enough. It'll need something similar to JinaAnalyzer and JinjaTracer, i.e.:
* Lexing the template tags
* Generating an auxiliary or alternative template which provides a full execution trace of the original template

**Comment by barrywhart** [comment]
This would be a separate project, in a different language, involving commercial software. Not a good fit for core SQLFluff. Closing.

**Comment by CobySim01** [comment]
I've implemented a very rough version of an SQLX linter and formatter using SQLFluff and Prettier. Feel free to contribute or raise issues on the [repo](https://github.com/CobySim01/sqlxfluff).

**Comment by vilozio** [comment]
> This would be a separate project, in a different language, involving commercial software. Not a good fit for core SQLFluff. Closing.

@barrywhart by any chance, do you know if there is ongoing development to support slqx in SQLFluff or elsewhere?

**Comment by barrywhart** [comment]
I haven't heard of anything. One of the SQLFluff maintainers mentioned at one point that he's done some work in Node, which I believe is the same language/platform that Dataform is implemented in, but as far as I know, he hasn't worked on it.

**Comment by mrmeszaros** [comment]
> I've implemented a very rough version of an SQLX linter and formatter using SQLFluff and Prettier. Feel free to contribute or raise issues on the [repo](https://github.com/CobySim01/sqlxfluff).

@CobySim01 This issue came up in our project. Do You think using a custom templater (likely based on the  `placeholder` templater) would be a viable solution?

Integrating it with prettier for the interpolated js/ts code could be handled separately.

PS.: Sorry for the zombification, but this is a very niche area and I try to use all the leads I can.

**Comment by moreaupascal56** [comment]
Hi there just letting everyone know that a templater for dataform have been developed here https://github.com/hiracky16/sqlfluff-templater-dataform/blob/main/pyproject.toml

It is good but I guess the author will welcome contributors 👍
