### ISSUE TITLE
Doc : Ignore parsing option missing from document

### ISSUE THREAD

**Issue by maxoja** [sqlfluff/sqlfluff#1762]
## URL or Command Line Option with the issue being reported

https://github.com/sqlfluff/sqlfluff/blob/main/src/sqlfluff/cli/commands.py#L188

## Issue/Suggested Improvement

There is no mentioning about this functionality to disable parsing errors from CLI using `--ignore parse` option. It's in the code but not in document. Barry Hart who answered my question on Slack found this. I just pass it on as an issue here.

**Comment by tunetheweb** [comment]
This is in the CLI docs: https://docs.sqlfluff.com/en/latest/cli.html and has been for a while now:

![image](https://user-images.githubusercontent.com/10931297/152385747-44c439b3-8ea3-46ff-bf20-06b6cfa7b3a6.png)

And btw it's `--ignore parsing` btw not `--ignore parse` - maybe that's why you couldn't find it?
