### ISSUE TITLE
Parsing fails on non-standard (but valid) table names when unquoted

### ISSUE THREAD

**Issue by drewmcdonald** [sqlfluff/sqlfluff#1793]
## Expected Behaviour

SQLFluff handles any valid table name for the database. Table names are _very_ permissive in BigQuery. From the [docs](https://cloud.google.com/bigquery/docs/reference/standard-sql/data-definition-language#table_path):
> For example, the following are all valid table names: `table 01`, `ग्राहक`, `00_お客様`, `étudiant-01`.

## Observed Behaviour

SQLFluff fails parsing when it encounters an unquoted table name that...

* begins with a number (e.g. `123_data`)
* contains non-alphanumeric characters (e.g. `a_á`)

### Table Names Beginning with a Number

unquoted

```bash
echo "SELECT x FROM project.dataset.123_data" > query.sql
sqlfluff parse --dialect bigquery query.sql
# L:   1 | P:  30 |  PRS | Line 1, Position 30: Found unparsable section: '.123_data'
```

quoted

```bash
echo "SELECT x FROM project.dataset.\`123_data\`" > query.sql
sqlfluff parse --dialect bigquery query.sql
# ok
```

### Table Names Containing non-standard Characters

**NOTE:** There may be some encoding issues here, as well (the differing input and output characters are true to how the parser raises the error for me)

unquoted

```bash
echo "SELECT x FROM project.dataset.xá" > query.sql
sqlfluff parse --dialect bigquery query.sql
# L:   1 | P:  32 |  LXR | Unable to lex characters: 'รก'
# L:   1 | P:  32 |  PRS | Line 1, Position 32: Found unparsable section: 'รก'
```

quoted

```bash
echo "SELECT x FROM project.dataset.\`xá\`" > query.sql
sqlfluff parse --dialect bigquery query.sql
# ok
```

## Dialect

BigQuery (potentially relevant to others)

## Version

```
Python 3.9.7
sqlfluff, version 0.7.1
```

## Configuration

no user configuration applied.

**Comment by lidalei** [comment]
In BigQuery, "Table name identifiers have additional syntax to support dashes (-) when referenced in FROM and TABLE clauses." [ref](https://cloud.google.com/bigquery/docs/reference/standard-sql/lexical#identifiers).

However, SQLFluff (version 0.8.2, Python 3.8.10) recognizes `-` as an operator. For example,
```shell
echo "SELECT x FROM project-id.dataset.data" | sqlfluff parse --dialect bigquery -
```
will cause two issues:
```
L:   1 | P:  22 | L006 | Missing whitespace before -                                                                                                                                    
L:   1 | P:  22 | L006 | Missing whitespace after -
```
A workaround is to quote table names with backtick `` ` ``.

**Comment by tunetheweb** [comment]
I've tested this in both the latest version of SQLFluff and BigQuery:

Test | SQLFLuff latest | BigQuery
-- | -- | --
123_data | OK | OK
a_á | Needs to be quoted in backticks | Needs to be quoted in backticks
table 01 | Needs to be quoted in backticks | Needs to be quoted in backticks
ग्राहक | Needs to be quoted in backticks | Needs to be quoted in backticks
00_お客様 | Needs to be quoted in backticks | Needs to be quoted in backticks
étudiant-01 | Needs to be quoted in backticks | Needs to be quoted in backticks
project-id.dataset.data | OK | OK


Therefore looks like we're aligned with BigQuery here.

The [documentation on identifiers](https://cloud.google.com/bigquery/docs/reference/standard-sql/lexical#identifiers) does say:

> Unquoted identifiers must begin with a letter or an underscore character. Subsequent characters can be letters, numbers, or underscores.

and

> Quoted identifiers can contain any character, such as spaces or symbols.

I don't know if non-ASCII counts as "symbols" instead of "letters" but that seems to be the case.

Weirdly the above implies `123_data` is not a valid identifier for a table, but it does seem to work (in both BigQuery and SQLFluff) so we'll leave that as is.

Let me know if you spot anything else you need think needs to be added here.
