### ISSUE TITLE
Progress bar issue with lint errors

### ISSUE THREAD

**Issue by tunetheweb** [sqlfluff/sqlfluff#1841]
@adam-tokarski noticed this today with the progress bar feature.

When you get lint errors, they interspace the progress bar, leaving an old copy of the bar around:

![Screenshot](https://user-images.githubusercontent.com/10931297/140654068-571dcbd1-a70d-4043-984e-b12e4e66838b.png)

It also makes the lints a tiny bit more difficult to read.

Is it possible to delete the progress bar lint before printing any lint error to avoid this?

**Comment by adam-tokarski** [comment]
Well, I could say that it gives some view on how it goes and on what step you were when something was reported, but it would be far-fetched I guess :slightly_smiling_face:.

Unfortunately it's because of mixed printing between `tqdm` and `click` as far I can say at this moment. 
I'm not sure how to handle this at this moment - the simplest solution would be to not print any lint messages as it happens, but rather buffer that somehow and then print it when everything - or at least current file -is processed. Otherwise it may be needed to put some hacking to handle that when formatter is pushing info using `click.echo` things 

I'll investigate that issue and thanks for reporting this.

**Comment by adam-tokarski** [comment]
@tunetheweb could you assign me to that issue?

**Comment by tunetheweb** [comment]
>  the simplest solution would be to not print any lint messages as it happens, but rather buffer that somehow and then print it when everything - or at least current file -is processed.

Downside of that is that you can't action errors as they happen and have to wait until the end.

**Comment by barrywhart** [comment]
Some brainstorming ideas; please think these through before spending much time -- not guaranteed to work!

Could we use cursor positioning to prevent this? E.g. record the cursor position before printing a lint error, move the cursor, print the error, then move it back? Could it be helpful to use a package like [textual](https://github.com/willmcgugan/textual)?

**Comment by adam-tokarski** [comment]
> Could we use cursor positioning to prevent this?

I'm afraid it slightly more complicated than that, but thanks to fact that `tqdm` delivers solutions which can be used in such problematic scenarios it's possible to handle it, hopefully. Till now I didn't find other situations that there would be left some progressbar artifacts.
