### ISSUE TITLE
Could not run sqlfluff - "Could not find adapter type redshift!"

### ISSUE THREAD

**Issue by robertdefilippi** [sqlfluff/sqlfluff#1929]
```
sqlfluff lint --dialect=redshift -v
==== sqlfluff ====
sqlfluff:                0.8.1 python:                  3.8.3
implementation:        cpython dialect:              redshift
verbosity:                   1 templater:                 dbt
dbt:                   =0.21.0

==== readout ====

=== [ path: /Users/me/development/work/profile_name/dbt ] ===

=== [dbt templater] Sorting Nodes...
Traceback (most recent call last):
  File "/Users/me/.pyenv/versions/3.8.3/lib/python3.8/site-packages/dbt/adapters/factory.py", line 65, in load_plugin
    mod: Any = import_module('.' + name, 'dbt.adapters')
  File "/Users/me/.pyenv/versions/3.8.3/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked

ModuleNotFoundError: No module named 'dbt.adapters.redshift'
```

## Expected Behaviour

I'm just trying out sqlfluff and I can't get it to run properly.  I know sqlfluff should able to be run Redshift, but it seems to be having a problem when I run Redshift and the dbt template together. I'm unsure how to debug this further because it seems all the paths are set correctly, and it is finding my dbt project and profiles directory correctly.

## Observed Behaviour

```
dbt.exceptions.DbtProfileError: Runtime Error
  Credentials in profile "profile_name", target "dev" invalid: Runtime Error
    Could not find adapter type redshift!
```
## Dialect

Redshift

## Version
```
❯ sqlfluff --version
sqlfluff, version 0.8.1

❯ python --version
Python 3.8.3
```

## Configuration
```
Include your SQLFluff configuration here

[sqlfluff]
verbose = 0
nocolor = False
dialect = redshift
templater = dbt
rules = None
exclude_rules = L009,L011,L019,L031,L034
recurse = 0
output_line_length = 160
runaway_limit = 10
ignore_templated_areas = True
encoding = autodetect
# Comma separated list of file extensions to lint.

# NB: This config will only apply in the root folder.
sql_file_exts = .sql,.sql.j2,.dml,.ddl

[sqlfluff:indentation]
indented_joins = False
indented_using_on = True
template_blocks_indent = True

[sqlfluff:templater:dbt]
project_dir = ./
profiles_dir = ~/.dbt/
profile = profile_name

```

**Comment by robertdefilippi** [comment]
Closing issue, as I believe the issue is with `dbt` and not `sqlfluff`

**Comment by amardeep** [comment]
How did you install dbt and sqlfluff?

Sqlfluff imports dbt as a python package - so they both need to be present in same (virtual) environment.

**Comment by robertdefilippi** [comment]
I have `dbt` installed with `brew`, so I can quickly switch between versions. Currently I'm using `0.20.0`

I also have python installed with `pyenv` so I can also switch between versions and environments.

When I installed `sqlfluff` using `pip` it overwrote / took priority over the `brew` version of `dbt` using `0.21.0` instead of the `0.20.0` I'm used to. Because the `0.21.0` version does not come with the redshift plugin installed, I was getting that error.

So now I'm trying to figure out how to get `sqlfluff` to use `brew` version of `dbt` instead of `pip` ... but that is a different issue.

**Comment by robertdefilippi** [comment]
> Sqlfluff imports dbt as a python package - so they both need to be present in same (virtual) environment.

If Sqlfluff needs to be in the same environment as dbt, are there any examples of Sqlfluff running from a docker container? Our production run of dbt comes from the official image, so how can I get Sqlfluff to play correctly with that setup?

**Comment by amardeep** [comment]
I am not familiar with python packaging and dependency management. Maybe reopen the bug (and/or discuss on slack) so that others can chime in.

Looking at [setup.py ](https://github.com/sqlfluff/sqlfluff/blob/0.8.1/plugins/sqlfluff-templater-dbt/setup.py#L66) though, it specifies `"dbt-core>=0.17"` - so I guess as long as you install dbt in some environment and install sqlfluff in same environment, it should be fine - for eg., following the approach in [this discourse post](https://discourse.getdbt.com/t/setting-up-your-local-dbt-run-environments/2353).

Same for docker - for eg. creating a new docker image based on official and installing sqlfluff in global environment with pip will possibly work (though I haven't tried it).

**Comment by 808sAndBR** [comment]
I had this issue but was able to resolve it by running `pip install dbt-redshift` in the venv that I am running sqlfluff in. This was unexpected as running `dbt --version` in that environment showed the plugins, but they must be coming from brew since the package was not present in `pip freeze` (although `dbt-core` and `dbt-extractor` were).

There is likely room for doc improvement maybe in the https://docs.sqlfluff.com/en/stable/configuration.html#installation-configuration section about needing to install this. Im not sure I understand the underlying issue / how and what sqlfluff installs when doing its own pip to make an exact suggestion though.
