### ISSUE TITLE
sqlfluff-templater-dbt 0.8.2 not on PyPI?

### ISSUE THREAD

**Issue by jdub** [sqlfluff/sqlfluff#1961]
Is it possible sqlfluff-templater-dbt 0.8.2 wasn't released to PyPI?

https://pypi.org/search/?q=sqlfluff

**Comment by tunetheweb** [comment]
Looks like the build failed: https://github.com/sqlfluff/sqlfluff/runs/4289258071?check_suite_focus=true

Here's an example of the last good run: https://github.com/sqlfluff/sqlfluff/runs/4289258071?check_suite_focus=true

It looks like this time it tried to build sqlfluff, rather than the sqlfluff-templater-dbt and then that failed t upload to PyPi as it wasn't built.

@jpy-git could you have a look and see if this is due to any of your recent changes?

**Comment by jpy-git** [comment]
👀

**Comment by tunetheweb** [comment]
That's now been released. Thanks for quick action @jpy-git !

**Comment by jdub** [comment]
Hooray, thanks!
