### ISSUE TITLE
Pass a configuration programmatically

### ISSUE THREAD

**Issue by jacopofar** [sqlfluff/sqlfluff#1983]
The [documentation](https://docs.sqlfluff.com/en/stable/api.html) shows it's possible to run linting and parsing programmatically, but I cannot find a way to pass a configuration when doing it, even after reading the code.

My use case is that I have a few folders with many SQL files containing placeholders that require templating, and want to parse these files without creating config files or generating one on the fly based on other sources.

Is it possible to specify a configuration programmatically as a `FluffConfig` object?

**Comment by jpy-git** [comment]
Hi @jacopofar, this has already been discussed a lot recently and I've started looking at implementing it. 

see #1244 for main discussion and we carried out poll yesterday on how people want the option implemented.

This will be passed as a path rather than a `FluffConfig`. Reasoning being we don't want to expose sqlfluff internals in the simple API.

Think we can close this issue as a duplicate.
