### ISSUE TITLE
TSQL: PRS error: multiple GO statements are not parsed

### ISSUE THREAD

**Issue by tkachenkomaria244** [sqlfluff/sqlfluff#2009]
Please add possibility to have multiple GO statements parsed in the TSQL scripts.

## Expected Behaviour
no parsing errors

## Observed Behaviour
```
CREATE TABLE [sch1].[table1] (
    [_id]         BIGINT         NOT NULL,
    [_date_from]     DATETIME       NULL,
    [_date_to]       DATETIME       NULL,
    [load_id]                 INT            NULL
);
GO

GO

GO
CREATE NONCLUSTERED INDEX [idx_table1_date_to]
    ON [dm_p3m].[position]([_id] ASC, [_date_to] ASC);


GO
CREATE CLUSTERED INDEX [idx_table1_date_from]
    ON [dm_p3m].[position]([_id] ASC, [_date_from] ASC);


```
```
==== parsing violations ====
L:   7 | P:   3 |  PRS | Line 7, Position 3: Found unparsable section:
                       | '\n\nGO\n\nGO\nCREATE NONCLUSTERED INDEX [idx_...'
```

## Dialect
TSQL

## Version
Python 3.9
SQLFluff 0.8.2

**Comment by jpy-git** [comment]
This issue also exists for semi-colon separated segments in non-tsql dialects:
This is perfectly valid SQL. It's just that some of the statements are empty.
![image](https://user-images.githubusercontent.com/80432516/146405750-8d0ab2b5-9285-4a04-88ab-a4b842f8a9b4.png)

Same idea holds for these multiple go statements, just with batch rather than statement.

Fix for this is fairly simple so will pull together.
