### ISSUE TITLE
Add SQL as a SQLFluff repository language

### ISSUE THREAD

**Issue by jpers36** [sqlfluff/sqlfluff#2032]
Github lists the repository's languages as 99.9% Python, 0.1% Dockerfile.  Is there a way we can get SQL represented?

**Comment by jpy-git** [comment]
@jpers36 It's an interesting one. The repo language ratio is handled by GitHub using the Linguist Library rather than manually by us. The Linguist repo (https://github.com/github/linguist#my-repository-is-detected-as-the-wrong-language) has some advice on debugging if the language ratio isn't as expected. So that'd be a good place to start if you were interested in investigating? 😄  

I guess the actual logic for SQLFluff is all Python and I don't think too many people care about the language split beyond which is the main one so more of a nice to have than essential.

**Comment by jpy-git** [comment]
Not sure if Linguist uses anything more complicated, but a naive check would indicate we should expect ~5% SQL files 

![image](https://user-images.githubusercontent.com/80432516/144688821-53139818-e924-4a4c-a003-3bf99a36b152.png)

**Comment by jpy-git** [comment]
Investigated a bit further. Linguist has a list of vendored file paths that are not excluded from the statistics and one of those is test/fixtures.

Including this constraint seems to explain why the sql isn't being included 
![image](https://user-images.githubusercontent.com/80432516/144689443-b31c1473-fc2c-40e9-82b5-4a94c019d141.png)

Linguist does provide a mechanism to override this default behaviour (https://github.com/github/linguist/blob/master/docs/overrides.md) so let me pull together a quick PR

**Comment by jpy-git** [comment]
Reopening as this still doesn't seem to include all of the SQL files

**Comment by jpy-git** [comment]
In addition to the vendored fix I added in the previous PR, Linguist also filters out non `programming` languages from its statistics: https://github.com/github/linguist/blob/master/docs/overrides.md#detectable

According to those docs we can override this with: `*.sql linguist-language=SQL linguist-detectable` in `.gitattributes`.
Annoyingly I can't test it locally as the `github-linguist` shell script won't pick up the `.gitattributes` but can confirm that if I change SQL to `programming` in the source code we get much more reasonable language stats.

Before:
![image](https://user-images.githubusercontent.com/80432516/147686014-a105bd6d-6052-485d-bcc9-604f289c6907.png)

After: 
![image](https://user-images.githubusercontent.com/80432516/147686041-418b2be7-bd78-44bf-8e7f-e3bde5bdcaf8.png)

Will make a PR to update `.gitattributes`

**Comment by jpy-git** [comment]
Yay looks good now 😎 
![image](https://user-images.githubusercontent.com/80432516/147692111-2bd430db-8520-401c-a5a8-3fc3f18d15b6.png)
