### ISSUE TITLE
Make Ref()s easy to follow in an IDE by using classes as arguments

### ISSUE THREAD

**Issue by chwiese** [sqlfluff/sqlfluff#2103]
Currently `Ref()` uses a string argument, which makes it somewhat cumbersome to find the class that is being referenced. Using search functionality in the IDE will also find all other Ref()s for that Segment, which can be quite numerous.
If `Ref()` used the actual class object as the argument, then one could use the Go to Definition functionality of the IDE to jump straight to the class being referenced, even across files.
There is relevant discussion on this in [this Slack thread](https://sqlfluff.slack.com/archives/C01GPHR8J0G/p1638824180165700), which suggests there might be a trade-off with lazy loading.

**Comment by jpy-git** [comment]
So after discussing with @barrywhart earlier, I remembered why the grammar uses string references to classes rather than the classes themselves.

The reason is SQL grammar can be recursive in nature. Consider the WITH statement and the SELECT statement. It's totally possible to have something like:
```sql
WITH cte1 AS (
     SELECT a FROM b
)

SELECT * FROM (
    WITH cte2 AS (
        SELECT *
        FROM cte1
    )

    SELECT * FROM cte2
);
```
That is to say, WITH grammar depends on SELECT grammar, which depends on WITH grammar, which depends on SELECT grammar etc. (also because of subqueries, SELECT grammar depends on SELECT grammar).

Using pseudocode for example purposes, you can see that there is no way you could define the two grammar classes referring to each other without one of them not existing at the time of the others definition.
```python
class WithStatement:
    match_grammar = ..., SelectStatement, ...

class SelectStatement:
    match_grammar = ..., WithStatement, ...
```
So this code would error as SelectStatement is not defined at the time of WithStatement definition (opposite if you switch them round).

Hence rather than directly referencing the other class we use a string reference to the other class and lazy load the grammar at parse time to allow for these recursive grammar definitions (so lazy loading is essential rather than just for performance reasons).

**Comment by jpy-git** [comment]
Closing due to reasons described above, best to remain with our current consistent approach.
