### ISSUE TITLE
TSQL: dialect-specific AlterTableStatementSegment

### ISSUE THREAD

**Issue by jpers36** [sqlfluff/sqlfluff#2201]
## Expected Behaviour

TSQL has a dialect-specific AlterTableStatementSegment which correctly represents the dialect's functionality.

## Observed Behaviour

TSQL relies on an ANSI-specific segment which does not fully represent TSQL functionality.

## Dialect

TSQL

**Comment by tunetheweb** [comment]
Rather than implement the full grammar (which looks to be quite large: AlterTableStatementSegment) I'd prefer to see specific asks for specific queries that currently don't parse. Think that is the best way to make progress and know when each issue has been addressed. At present it's very difficult to know if this issue has been addressed.

So going to close for now and suggest you open a new issue with an example SQL for any additions required here.
