### ISSUE TITLE
distutils deprecation warning

### ISSUE THREAD

**Issue by grawlinson** [sqlfluff/sqlfluff#2262]
```
/usr/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
/usr/bin/python -Wignore:The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives:DeprecationWarning
```

3.12 will be released shortly, it will be best to switch out sooner rather than later.

**Comment by jpy-git** [comment]
@grawlinson we're not using distutils so this has nothing to do with sqlfluff.

As the warning clearly states you are the one using `setup.py` to install the package.
Since I remember you posting previously about your unofficial AUR package I've looked and that is indeed the case:
![image](https://user-images.githubusercontent.com/80432516/148685688-104ae6d6-ff30-4904-829c-04053498333d.png)
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=sqlfluff&id=5ed31aa5470944db36cadf4c6471f09add36d812

In your case the warning says, you should either:
- install via pip: `python -m pip install .`
- build the source dist/wheel via `build`: `python -m build --sdist --wheel .` and then install that.

**Comment by jpy-git** [comment]
CLOSING: As I mentioned in #2112 your AUR package is not officially supported by us so you should be able to work through these things yourself.
