### ISSUE TITLE
Slow parsing/linting performance for a large INSERT query

### ISSUE THREAD

**Issue by tdstark** [sqlfluff/sqlfluff#2269]
## Expected Behaviour
The following query takes 20-35 minutes to lint using the Redshift dialect depending on the machine it's running on:
```
INSERT INTO schema.table1
  (
    col1,
    col2,
    col3,
    col4,
    col5,
    col6,
  )
  VALUES
  (10068, 10171, 'string', 605),
  (10057, null, 'string2', 62),
  (10140, null, 'string3', null, null, null);
```
The values portion is multiplied by approximately 1100 lines

## Observed Behaviour
The following query takes 20-35 minutes to run using the Redshift dialect. Given other discussions on Slack, I suspect that this is a problem for all dialects.

## Steps to Reproduce
Run the aformentioned query.

## Dialect
`--dialect=redshift`

## Version
`0.9.1`

## Configuration
Default config

**Comment by afreickmann** [comment]
I assume that parsing the many elements is slowing down the process. When I replace the quotes and unnecessary commas in the query, the speed of processing changes from 7min to 3min. Removing the huge concats completely changes processing time to 1 minute, but this might be just because of reducing lines => fixing symptom, not root cause.
Would be great, if this could be increased to a reasonable processing speed as in our company.

[item_availability_step_3_part_1.txt](https://github.com/sqlfluff/sqlfluff/files/7839287/item_availability_step_3_part_1.txt)
[item_availability_step_3_part_1_no_commaquotes.txt](https://github.com/sqlfluff/sqlfluff/files/7839246/item_availability_step_3_part_1_no_commaquotes.txt)

**Comment by tunetheweb** [comment]
@WittierDinosaur since you did the last optimisation work, do you have any capacity to look at this?

**Comment by tunetheweb** [comment]
This was the PR that magically fixed a SELECT statement of mine with thousands of `UNION`'s of very similar SQL: https://github.com/sqlfluff/sqlfluff/pull/1744

But how that magically made it better is beyond me! 😁

**Comment by WittierDinosaur** [comment]
So, the issue is that both `Delimited` and `Bracketed` are very expensive in terms of performance. I have a branch where I'm working on dealing with Delimited, but it's a rabbit hole, ad i haven't quite resolved all of the issues yet. Also been relatively offline recently, because i've been focusing on work things. I'll push the branch tonight for visibility

**Comment by tdstark** [comment]
@WittierDinosaur I'm still willing to dig into this a bit if you point me in the right direction! I'm not sure how far I will get but I'm willing to give it a shot.

**Comment by jpy-git** [comment]
Just ran into a similar issue.

An analyst submitted a PR with a query along the lines of:
```sql
SELECT
    *
FROM
WHERE id IN (
1,
3,
4,
5,
7,
11,
...
x10000
)
```
I assume the context is they were given a long list of ids in excel and the quickest way to do analysis was to paste them into the query. The query is fine for a quick ad-hoc request, but it caused the CI to hang when being linted so I've just added it to sqlfluffignore in the meantime. Pretty sure slow delimited parsing is the culprit.

On a side note, maybe we can have an optional timeout param in the config/cli that allows a user to skip a file if the parsing takes too long.

**Comment by siddhant-ti** [comment]
The codebase that I've ran sqlfluff so far mostly contains lots of procedures
I am ok with it taking hours for some files, but recently when I ran it on file having 8K lines of sql code (full of procedures), it took 2 hours to process first 100 lines, that means it might take approx a week to process such file

Having optional timeout param looks good as well

**Comment by WittierDinosaur** [comment]
@tdstark #2831 takes it down to about 8 minutes for linting. I'll leave it with you as to whether that's enough to close this bug report. It's about half and half parsing and linting now. Bracketed() eats up most of the performance of the parser now, and I'll be working on that soon. Performace of the linter is something that I'll be looking at in the near-ish future

**Comment by tdstark** [comment]
@WittierDinosaur I think that's fine for now. I haven't done any testing, but that's a reduction of ~2/3 which is great! Let me know if you want help when you get into the `Bracketed()` work.
