### ISSUE TITLE
begin/rollback/commit tran is not supported

### ISSUE THREAD

**Issue by fdw** [sqlfluff/sqlfluff#2368]
While sqlfluff has no problem parsing `begin transaction` (or `rollback transaction`, `commit transaction`), at least in T-SQL there is also the shorter form `begin tran` (`rollback tran`, `commit tran`) (f.e. https://docs.microsoft.com/en-us/sql/t-sql/language-elements/rollback-transaction-transact-sql?view=sql-server-ver15).

First, it would be nice if `sqlfluff` could parse this, too. Secondly, I could imagine a rule to align these to either always the short form or always the long one.

**Comment by tunetheweb** [comment]
This would be another nice and simple one. Just replace a instances of `"TRANSACTION"` with `OneOf("TRANSACTION","TRANS")`.

Or better yet create a Grammar (`TransactionGrammar`) that has that and use that in place of all current instances of `"TRANSACTION"`. In fact this might be one to add to `dialect_ansi.py` and have every dialect inherit it since I think most dialects support this.

Then a couple of test cases and bish bosh job done.

**Comment by jpy-git** [comment]
> Secondly, I could imagine a rule to align these to either always the short form or always the long one.

^ This reminded me of a rule suggestion I'd read a while back and it would make more sense to make a fix for something like this general so I've opened a suggestion for that.

This issue should just address the grammar fix suggested by @tunetheweb above 😄

**Comment by fdw** [comment]
So, this change seems easy enough to try, but I still need a pointer.

First, `BEGIN TRAN` and friends seem to be T-SQL-specific, so I'd only add it to `dialect_tsql.py`. Secondly, since `"WORK" ` is already a synonym in some cases, I'd prefer to not add a new Grammar, but use `OneOf`.
Is that reasonable?

Finally, I have no idea where to test this. I looked in `test/dialects`, but there is nothing for T-SQL yet. Any help please?

**Comment by tunetheweb** [comment]
> So, this change seems easy enough to try, but I still need a pointer.

Sure! Happy to help. These sorts of changes are pretty simple for a regular maintainer to add, but would rather spread the knowledge so you can help self-serve in future. Plus you'll likely know a lot more about the dialect you use (I don't use T-SQL for example). So definitely happy to answer any questions to help make that happen!

> First, `BEGIN TRAN` and friends seem to be T-SQL-specific, so I'd only add it to `dialect_tsql.py`.

Sounds good. Though it was more generic, but maybe it isn't. Let's start with T-SQL and can generalise in future if needs be.

> Secondly, since `"WORK" ` is already a synonym in some cases, I'd prefer to not add a new Grammar, but use `OneOf`. Is that reasonable?

Oh that's a good spot. But in that case I think that makes a good case for adding a new grammar! Let me explain. At the top of each dialect we have a set of simple Grammars such as:

```py
ansi_dialect.add(
    ...
    LikeGrammar=OneOf("LIKE", "RLIKE", "ILIKE"),
    ...
```

These can then be replaced in other grammars for more appropriate ones:

```py

tsql_dialect.replace(
    ...
    # Replace ANSI LikeGrammar to remove TSQL non-keywords RLIKE and ILIKE
    LikeGrammar=Sequence(
        "LIKE",
    ),
    ...
```

This is really useful, because it means any generic statements that T-SQL inherits from ANSI will also have the T-SQL definition of `LikeGrammar`! This saves having to override ANSI classes if that is the only difference.

So I would suggest the following changes:
1. Add a simple `TransactionGrammar` to ANSI for `OneOf("TRANSACTION", "WORK")`
2. Replace all occurrences (in all dialects) of `OneOf("TRANSACTION", "WORK"),` with `Ref("TransactionGrammar"),` and all occurrences of `OneOf("TRANSACTION", "WORK", optional=True),` with `Ref("TransactionGrammar", optional=True),`
3. Override the `TransactionGrammar` in T-SQL to `OneOf("TRANSACTION", "TRANS")`
4. Replace all occurrences of `"TRANSACTION",` in T-SQL with `Ref("TransactionGrammar"),`.

Does that make sense? It's a bit of a bigger change than originally envisaged, but think this is the right change to make. If you're not comfortable making this level of change for your first PR (understandable!) then let me know and I can have a look at it today, since it's a bit more than originally envisaged.

> 
> Finally, I have no idea where to test this. I looked in `test/dialects`, but there is nothing for T-SQL yet. Any help please?

Simple tests are in `test/fixtures/dialects/tsql`. Each test is in two formats:
1. A SQL file - this is what you're supposed to write.
2. A YML file - this is the parse tree and is automatically generated from the SQL by running `python test/generate_parse_fixture_yml.py`. We commit this as well as the SQL to allow us to easily see any diffs in the parse tree in future in case the were unintended.

**Comment by fdw** [comment]
Thanks for that, it's *really* helpful! 🙂

I'll play with it some more, but the problem I see currently is that (at least for T-SQL), "WORK" is not always a valid synonym, but only sometimes (f.e. `ROLLBACK WORK` is fine, but `BEGIN WORK` is not). So, I think I'd have to look into ANSI to see whether `WORK` should be generally supported or not, and then overwrite it almost everywhere, maybe on statement level :/

**Comment by tunetheweb** [comment]
Ah ok. See this is why it helps having the dialect users making the change 😁

You’ve two choices:
1. have a `TransactionGrammar` and a `TransactionOrWorkGrammar` and use appropriately in each statement. The T-SQL versions can include `TRANS` shorthand.
2. Just use one and allow `WORK` everywhere and accept that some statements will not be 100% perfectly set up in SQLFluff (as they aren’t right now!).

**Comment by tunetheweb** [comment]
Change looks good to me from a high level so happy for this approach. Can generalise later if needs be.
