### ISSUE TITLE
UPDATE statements are not parsed in Redshift dialect

### ISSUE THREAD

**Issue by rpr-ableton** [sqlfluff/sqlfluff#2416]
## Expected Behaviour
Since Redshift UPDATE syntax is similar to the postgres and ANSI one, it shouldn't error out because it inherits from postgres (which in turns inherits it from ANSI).

I think I'm missing something obvious but since the below statements parse without any error both in ANSI and postgres dialect, I can't cog why it wouldn't when dialect is set to Redshift.

## Observed Behaviour
SQLFluff is unable to parse any UPDATE statement in the Redshift dialect. For example:

```
[L:  1, P:  1]      |file:
[L:  1, P:  1]      |    statement:
[L:  1, P:  1]      |        update_statement:
[L:  1, P:  1]      |            unparsable:                                       !! Expected: 'UpdateStatementSegment'
[L:  1, P:  1]      |                keyword:                                      'update'
[L:  1, P:  7]      |                whitespace:                                   ' '
[L:  1, P:  8]      |                raw:                                          'tbl1'
[L:  1, P: 12]      |                newline:                                      '\n'
[L:  2, P:  1]      |                raw:                                          'set'
[L:  2, P:  4]      |                whitespace:                                   ' '
[L:  2, P:  5]      |                raw:                                          'col1'
[L:  2, P:  9]      |                whitespace:                                   ' '
[L:  2, P: 10]      |                raw:                                          '='
[L:  2, P: 11]      |                whitespace:                                   ' '
[L:  2, P: 12]      |                raw:                                          'col2'
[L:  2, P: 16]      |    statement_terminator:                                     ';'
[L:  2, P: 17]      |    newline:                                                  '\n'
[L:  3, P:  1]      |    newline:                                                  '\n'
[L:  4, P:  1]      |    statement:
[L:  4, P:  1]      |        update_statement:
[L:  4, P:  1]      |            unparsable:                                       !! Expected: 'UpdateStatementSegment'
[L:  4, P:  1]      |                keyword:                                      'update'
[L:  4, P:  7]      |                whitespace:                                   ' '
[L:  4, P:  8]      |                raw:                                          'tbl1'
[L:  4, P: 12]      |                newline:                                      '\n'
[L:  5, P:  1]      |                raw:                                          'set'
[L:  5, P:  4]      |                whitespace:                                   ' '
[L:  5, P:  5]      |                raw:                                          'col1'
[L:  5, P:  9]      |                whitespace:                                   ' '
[L:  5, P: 10]      |                raw:                                          '='
[L:  5, P: 11]      |                whitespace:                                   ' '
[L:  5, P: 12]      |                raw:                                          "'foo'"
[L:  5, P: 17]      |    statement_terminator:                                     ';'
[L:  5, P: 18]      |    newline:                                                  '\n'
```

## Steps to Reproduce
Any valid UPDATE statement. For example:
```
update tbl1
set col1 = col2;

update tbl1
set col1 = 'foo';
```
## Version

sqlfluff, version 0.9.1
Python 3.9.5

## Configuration
```
[sqlfluff]
dialect = redshift
```

**Comment by tunetheweb** [comment]
This is due to the fact that `SET` is not a reserved word in Redshift.

Therefore it's allowed to be used as a table alias. So:

```sql
update tbl1
set col1 = col2;
```

Is read by SQLFluff as:

```sql
update tbl1 as set
col1 = col2
```

And it doesn't understand that.

The easiest answer in this case is to make `SET` reserved and then it'll parse. Though that might not technically be accurate since, according to [the documentation](https://docs.aws.amazon.com/redshift/latest/dg/r_pg_keywords.html) it's not reserved.

However SHOULD `set` be reserved? Could you run something like this and confirm if it works?

```sql
SELECT *
FROM example_table AS SET
```

If that's not valid RedShift SQL then definitely should just make it a reserved word.

**Comment by rpr-ableton** [comment]
Ah, true!

Yep, the above statement does work, `SET` doesn't seem reserved in any way :no_mouth:

**Comment by jpy-git** [comment]
I've encountered this exact issue recently as well and ended up giving up trying trying to fix it.

It's actually a bit borked in Postgres as well but is currently parsing due to an oversight in how the keywords are defined, SET is both reserved and unreserved (will open a separate issue for that)!

But yes, as @tunetheweb mentioned it did parse when I made `SET` reserved but that then doesn't allow it to be used as an alias, which is valid in both Postgres and Redshift.

**Comment by jpy-git** [comment]
Quick demo of the insanity that is Postgres keywords 🤯 
![image](https://user-images.githubusercontent.com/80432516/150636354-a19d6dd6-6e85-427c-8dd0-62df9cc0956b.png)

**Comment by tunetheweb** [comment]
I've for a fix. PR coming up.

**Comment by tunetheweb** [comment]
https://github.com/sqlfluff/sqlfluff/pull/2417

Think we should revert "SET" back to unreserved for Postgres in that PR too?

**Comment by jpy-git** [comment]
@tunetheweb it's because Postgres inherits from ANSI and therefore keeps its keywords
It then updates the set to add its own keywords but never removes the ANSI ones:
![image](https://user-images.githubusercontent.com/80432516/150636906-cc35268d-c384-407d-ac57-f35643667fa8.png)

Postgres keywords are very thorough, so pretty sure we just need to clear the ANSI keywords before we do the updating?
i.e.
```python
postgres_dialect.sets("reserved_keywords").clear()
postgres_dialect.sets("unreserved_keywords").clear()
<usual postgres keyword updating>
```

**Comment by tunetheweb** [comment]
OK will leave that for another time then. Feel free to raise an issue for it so we don't forget if you want.

**Comment by jpy-git** [comment]
Yeah I'll test it out now and if it's a more involved change will make an issue 👍

**Comment by jpy-git** [comment]
Also the reason I encountered this error initially was I was updating the `EXPLAIN` statement as I recently updated the Postgres one and the Redshift one is different. Going to finish that off once we merge in #2417
