### ISSUE TITLE
'click.shell_completion' install errors

### ISSUE THREAD

**Issue by tdstark** [sqlfluff/sqlfluff#2519]
Github Actions and my local installation keep throwing issues related to `click`:
```
--Error detail:
Traceback (most recent call last):
  File "/usr/local/bin/sqlfluff", line 5, in <module>
    from sqlfluff.cli.commands import cli
  File "/usr/local/lib/python3.9/site-packages/sqlfluff/cli/commands.py", line 28, in <module>
    from sqlfluff.cli.autocomplete import dialect_shell_complete
  File "/usr/local/lib/python3.9/site-packages/sqlfluff/cli/autocomplete.py", line 3, in <module>
    from click.shell_completion import CompletionItem
ModuleNotFoundError: No module named 'click.shell_completion'
```
This is likely due to the version in our setup.cfg file being out of date, see [this](https://github.com/sqlfluff/sqlfluff/blob/main/setup.cfg#L69).

## Expected Behaviour
SQLFluff should install all requirements without issue.

## Observed Behaviour
SQLFluff does not install all requirements as expected.

## Steps to Reproduce
Install SQLFluff in a new environment.

## Dialect
N/A

## Version
`0.9.3`

## Configuration
Default

**Comment by barrywhart** [comment]
Quick note about the instructions to reproduce: Simply installing it will probably work, because by default, unconstrained requirements choose the latest version. Possibly, megalinter is choosing an older version in order to co-exist with some other packages in the same environment, or perhaps updating things as little/slowly as possible. Sometimes people do this in order to minimize changes and reduce risk of breaking things. It's sometimes a good idea, the risk is exactly this -- it breaks projects that accidentally aren't requesting the correct minimum versions. Argh.

Anyway, we have a fix now.
