### ISSUE TITLE
sqlfluff changes case of UDF functions

### ISSUE THREAD

**Issue by awoehrl** [sqlfluff/sqlfluff#2700]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

I have sqlfluff set to lowercase all sql functions. However this also changes the case of UDF functions, which are case sensitive.

```sql
{{target.schema}}_functions.decodeEntities(
            nullif(coalesce(product_brand, impression_product_brand), '')
        ) as product_brand
```

will be transformed to

```sql
{{target.schema}}_functions.decodeentities(
            nullif(coalesce(product_brand, impression_product_brand), '')
        ) as product_brand
```

```
[sqlfluff:rules:L010]
capitalisation_policy = lower
```

### Expected Behaviour

Ignore the case of UDF functions

### Observed Behaviour

Changed case for UDF functions

### How to reproduce

This is the settings rule:

```
[sqlfluff:rules:L010]
capitalisation_policy = lower
```

### Dialect

BigQuery

### Version

0.10.1

### Configuration

```
[sqlfluff:rules:L010]
capitalisation_policy = lower
```

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by barrywhart** [comment]
Is there a way for SQLFluff to know which functions are UDFs? In general, SQLFluff doesn't have a list of built-in functions, so unless it can determine UDFs somehow from the syntax, there may not be a good fix possible for this.

**Comment by awoehrl** [comment]
I think it could work for temp functions as these are defined in the same query and thus sqlfluff could derive the function name:

```CREATE TEMP FUNCTION lastArrayElement(arr ANY TYPE) AS (
  arr[ORDINAL(ARRAY_LENGTH(arr))]
);

SELECT lastArrayElement(x) as last_element
  FROM (SELECT [2,3,5,8,13] as x)```

For materialized functions I'm not so sure. The only 

```CREATE FUNCTION mydataset.AddFourAndDivide(x INT64, y INT64)
  RETURNS FLOAT64
  AS ((x + 4) / y);
```
The only clue could be that these have to specify the dataset when called:
```
SELECT val, mydataset.AddFourAndDivide(val, 2)
  FROM UNNEST([2,3,5,8,12]) AS val;
```

Off the top of my head I can only think of the "safe." prefix that would have a similiar syntax:

```
SELECT SAFE.SUBSTR('foo', 0, -2) AS safe_output UNION ALL
SELECT SAFE.SUBSTR('bar', 0, 2) AS safe_output;

+-------------+
| safe_output |
+-------------+
| NULL        |
| ba          |
+-------------+
```

**Comment by tunetheweb** [comment]
I’m a bit confused. You talked about rule L010, but it’s L030 which enforces function and capitiaisation?

Assuming it is L030, then there’s a few options:
1. Allow camelCase as an option (first letter must be lowercase but uppercase allowed within), though your last example is PascalCase so maybe need that too but then becomes difficult to differentiate from uppercase.
2. Add option to ignore any qualified function name (I.e. with schema and dot).
3. Just add `noqa` or `ignore_words` for the function you don’t want this rule to apply to.
4. Turn this rule off if not useful for you.

To be honest I turn L030 off because
I also use camelCase UDF function names. I’m not sure why you’d want lowercase for system functions but not for UDFs?

**Comment by awoehrl** [comment]
@tunetheweb, I didn't realize that function and keyword capitalisation were two separate rules. Thanks for pointing that out!  As you suggested, I will turn off rule L030 and can still have enforcement of lowercase keywords via L010.
Thanks!
