### ISSUE TITLE
Support Pascal Case for L030

### ISSUE THREAD

**Issue by fdw** [sqlfluff/sqlfluff#2736]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### Description

It often makes sense to have function names as PascalCase, for example `DateAdd` or `IsNull`. Unfortunately, L030 only offers `upper`, `lower` and `capitalize`, which are all less than ideal for these cases.

### Use case

I would like my function names to be easily readable. For names that consist of multiple words, PascalCase makes the most sense.

### Dialect

At least T-SQL, but probably relevant for all dialects.

### Are you willing to work on and submit a PR to address the issue?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by tunetheweb** [comment]
Can you be clear what you mean by PascalCase here?

I presume you mean:
- Starts with a capital letter? Or happy with pascalCase too?
- Has at least one lowercase letter? Or is EXAMPLE still valid PascalCase?
- Depending on above should it end in a lower case?
- For Autofix the best we could do is initial capital letter (e.g. `examplefunction` or `EXAMPLEFUNCTION` would both be autofixed to `Examplefunction` rather than `ExampleFunction` which is probably the right answer but impossible to really get a system to understand)? Or should PascalCase not be Autofix compatible so always will require manual intervention?
- Should it convert snake case? E.g. `pascal_case` is converted to `PascalCase`?

Depending on answer to those (particularly the second one) it might be best to just turn off rule L030 rather than add to it.

**Comment by fdw** [comment]
As L014 already has PascalCase, I thought it could and should use the same logic 🙂

**Comment by fdw** [comment]
That was fast, thank you!

**Comment by tunetheweb** [comment]
Luckily was simple once you pointed me in the right direction! 😁
