### ISSUE TITLE
Snowflake: Parsing Error on bracketed subclause

### ISSUE THREAD

**Issue by WittierDinosaur** [sqlfluff/sqlfluff#3182]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

In Snowflake - this is parsable:
```
  SELECT foo
    FROM(
        SELECT foo
            FROM bar
            )GROUP BY 1)
```

### Expected Behaviour

The above parses

### Observed Behaviour

The lack of whitespace between the `)` and `GROUP BY` throws a parsing error

### How to reproduce

sqlfluff parse the above

### Dialect

Snowflake

### Version

0.13.0

### Configuration

N/A

### Are you willing to work on and submit a PR to address the issue?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by tunetheweb** [comment]
You've an extra bracket at the end which is invalid.

However, removing that, I see it's still an error and it's due to this `enforce_whitespace_preceding_terminator=True,`:

https://github.com/sqlfluff/sqlfluff/blob/e5eb5025f944db4f0830e66799b31ce0d3a9ea66/src/sqlfluff/dialects/dialect_ansi.py#L1515-L1519

Which was added here: https://github.com/jpers36/sqlfluff/commit/655dea368625495a1d7cd56cf3afea1911733291

To allow parsing the likes of this in Snowflake:

```sql
select
    value:data:to::string AS TO_PHONE_NUMBER,
    value:data:from::string AS FROM_PHONE_NUMBER
FROM a.b.ticket_audits
```

Need to decide how to handle that case, if reverting this change.
