### ISSUE TITLE
Grammar issue/question: Why are there "G", "K", and "M" keywords?

### ISSUE THREAD

**Issue by barrywhart** [sqlfluff/sqlfluff#322]
In the file `sqlfluff/dialects/ansi_keywords.py`, I noticed three one-letter keywords: G, K, and M. I discovered these when one of our queries aliased a table as the single letter `m`, and it generated a `sqlfluff lint` warning not to use keywords as an alias.

Are there really variants of SQL where these are keywords?

While this was a pretty minor nuisance (renaming the alias), it made me wonder about whether it may be useful to split out some of these unusual keywords. The more there are, the more likely a user is to see "false positive" warnings like I saw, i.e. being warned about a keyword which is not a keyword in the version of SQL they're actually using.

**Comment by alanmcruickshank** [comment]
Apparently yes: https://www.postgresql.org/docs/8.1/sql-keywords-appendix.html

I like your idea though of rather than having two lists of keywords we have three.

Currently we have:
- `reserved_keywords`: These generate keywords automatically and also actively cannot be identifiers (i.e. the parser will not parse them as identifiers).
- `unreserved_keywords`: There automatically generate keywords and also raise linting errors if used for identifiers.

I wonder if we should have three groups:
- `reserved_keywords`: _as above_
- `unreserved_linted_keywords`: Same behaviour as `unreserved_keywords` above
- `unreserved_unlinted_keywords`: Automatically generates keywords, but doesn't raise linting errors.

That last group would contain some of the less common keywords `G`, `K`, `M` but also keywords like `VALUE` or `USER` which are very commonly used in queries but I don't think are a sign of bad practice.

I'm curious to what @Katzmann1983 thinks on this topic. Thoughts?

**Comment by barrywhart** [comment]
Adding a third group sounds good to me.

**Comment by NiallRees** [comment]
I'm going to close this issue as i believe the original question has been answered! But let's create a new issue if needed
