### ISSUE TITLE
L032 rationale no longer exists

### ISSUE THREAD

**Issue by jivanpal** [sqlfluff/sqlfluff#3310]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### Links or command line

- L032: https://docs.sqlfluff.com/en/stable/rules.html#sqlfluff.core.rules.Rule_L032
- dbt Style Guide: https://github.com/dbt-labs/corp/blob/main/dbt_style_guide.md
- Change to Style Guide in question: https://github.com/dbt-labs/corp/commit/67ff0c5819bd0ee39963ff065667d7c96ca1fbc7

### Issue/Suggested Improvement

The rationale given for L032 that was found in the dbt Style Guide no longer exists in the Style Guide as of 4 Feb 2022. In light of this, the documentation should probably be updated, and perhaps it is worth considering disabling the rule by default.

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by tunetheweb** [comment]
Agree it probably should be changed to "This rule was originally taken..." and maybe a note that even they have changed it.

> perhaps it is worth considering disabling the rule by default.

We recently introduced rule groups, with `core` and `all` being the first two groups supported. This rule did not make it into `core`.

We still default to running `all` rules so that users are aware of all the rules we have, and can make a conscious choice to exclude some (either by using `core`, or by selecting the exact rules they want - or a combination of the two).

**Comment by tunetheweb** [comment]
Agree it probably should be changed to "This rule was originally taken..." and maybe a note that even they have changed it.

> perhaps it is worth considering disabling the rule by default.

We recently introduced rule groups, with `core` and `all` being the first two groups supported. This rule did not make it into `core`.

We still default to running `all` rules so that users are aware of all the rules we have, and can make a conscious choice to exclude some (either by using `core`, or by selecting the exact rules they want - or a combination of the two).
