### ISSUE TITLE
Ignore PRS errors on keywords level

### ISSUE THREAD

**Issue by ohyan** [sqlfluff/sqlfluff#3315]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### Description

We are using SQLFluff with BigQuery. And we use some procedural language in the query, such as `FOR…IN` .(ref: https://cloud.google.com/bigquery/docs/reference/standard-sql/procedural-language#for-in)
We got PRS  error like below.
```L: 18 | P:  4 | PRS | Line 18, Position 4: Found unparsable section: ' FOR'```

I know that `--noqa: RPS` will work to ignore this error, but we got a lot of files to modify.
It will be much helpful if we can ignore PRS errors on keywords level.

### Use case

Setting `ignore_words = None` in configuration file for PRS.

### Dialect

`ignore_words=[FOR, IN, ASSERT, ...]`

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by tunetheweb** [comment]
This can’t really work. Parsing is done before rules run and the `ignore_words` setting is a rule setting.

We do have the `ignore` setting but agree that is not that fine-grained and more of an all or nothing setting.

Since SQL with parsing errors (even if ignored) is code that SQLFluff doesn’t understand, so will always be difficult to work around.

Given that, I’d rather concentrate on adding that syntax support to SQLFluff rather than enhance ignore options for parsing errors.

So going to close this issue and ask you to raise another for the syntax you want supported.
