### ISSUE TITLE
SOQL: Disallow `SELECT *` and `COUNT(*)`

### ISSUE THREAD

**Issue by greg-finley** [sqlfluff/sqlfluff#3324]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### Description

SOQL doesn't let you select columns with `*`.

### Dialect

soql

### Are you willing to work on and submit a PR to address the issue?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by barrywhart** [comment]
When you say "disallow", can you clarify what you mean:
* It should result in a parse error.
* A rule should warn you not to do it.
* Other?

Often in SQLFluff, we have (for pragmatic reasons) implemented dialects so that things parse which are not actually supported. For example, I believe the ANSI dialect implements some Postgres-specific syntax, which thus parses in other dialects.

In general, you should not count on successful parsing in SQLFluff to guarantee that the SQL will parse in the actual database. We are more concerned with the opposite (SQL that does not parse in SQLFluff but does parse in the target database.)

**Comment by tunetheweb** [comment]
I think he just means to update the grammar to remove this as an option. SOQL seems to be a pretty simple, and limited SQL dialect as far as I can tell.

We could just base this on ANSI grammar and let the extras go, but think @greg-finley ’s intent (based on last PR) is to massively reduce the SQL it allows by simplifying the grammar it’s inherited from ANSI. As opposed to what we normally do to expand the ANSI dialect with additional syntax.

**Comment by greg-finley** [comment]
If you did `SELECT * FROM Account` in SOQL, it wouldn't work.

I am fine to close all of these "remove stuff from ANSI" tickets. 👍  What do you think?

**Comment by greg-finley** [comment]
Per https://github.com/sqlfluff/sqlfluff/issues/3324#issuecomment-1126525606
