### ISSUE TITLE
Parser: Bracketed should just be a sequence with brackets tacked on

### ISSUE THREAD

**Issue by WittierDinosaur** [sqlfluff/sqlfluff#3388]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### Description

Currently Bracketed() conjures _bracket_sensitive_lookahead_match and its child _lookahead_match(). These cause recursion, increasing the time complexity of the function. They shouldn't be necessary. Wonky brackets wouldn't parse anyway, and the grammar should never be in a position where it's swallowing brackets. It should match like a sequence does, build the Segment, and return.

### Dialect

N/A

### Are you willing to work on and submit a PR to address the issue?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by tunetheweb** [comment]
This this require fixing #3345 ? Or could we fix this at the same time?

**Comment by WittierDinosaur** [comment]
We could do, depends if you want them to be bracket pairs. For your issue, could you not instead do
```
match_grammar = Sequence(
    "BEGIN",
    Anything(),
    "END"
)
```
?

**Comment by tunetheweb** [comment]
No, because of nesting. What’s to stop that closing the match from below after the first `END` and producing an unparsable result because of this?

```
BEGIN
  BEGIN
  ...
  END
END
```

To me it’s the same with nested brackets.

I still think it can be `O(n)` - just need a counter of the open brackets (or `BEGIN`s) and don’t close it out until you get to zero.

**Comment by WittierDinosaur** [comment]
Hmm, yeah, I'd perhaps not considered that case. Would you not want though, in this case, your second block to not be treated as a raw type?

**Comment by WittierDinosaur** [comment]
Because the thing with your issue, is that any time we used the greedy set of things, everything in the payload in considered raw

**Comment by tunetheweb** [comment]
At the moment `StartsWith` With terminator or `GreedyUntil` terminates on first match.

I want a new `Balanced` type that is like `GreedyUntil` but won’t allow early closing.

As I say I think it could be implemented by having a `StartClause` and an `EndClause`. We increment a counter each time we see a `StartClause` and decrement for an `EndClause` and end the match when the `EndClause` is reached AND the counter is 0. No negative look ahead needed.

So that would also work for brackets:

```sql
SELECT (1 + (2 * 3))
```

**Comment by tunetheweb** [comment]
And the `StartsClause` and `EndClause` should allow multiple values to handle this case:

```
BEGIN
  IF
      ....
  END IF
END
```

**Comment by WittierDinosaur** [comment]
Yeah, I reckon that's a good idea. I wouldn't want it for brackets, I think it should only have scope on Greedy things. Rebuilding brackets as above will allow nesting in brackets, it just would be unrelated to your nesting troubles

**Comment by tunetheweb** [comment]
Why wouldn’t you want same thing for brackets? I presumed the reason for the negative look aheads in brackets is to prevent matching an opening bracket without a closing bracket for nested brackets (though haven’t looked into it, that’s just a presumption). So isn’t it the same thing?

Otherwise how would you match this `SelectElementClause` without ending it early after first `)`?

```sql
SELECT (1 + (2 * 3))
```

**Comment by tunetheweb** [comment]
I don’t think you’ll be able to get away with just defining the Grammar with an opening bracket and a closing bracket at either end if that’s what you mean? The possibilities that opens up without narrowing the match to a balanced closing bracket could mean nearly endless combinations to check between now and the end of the statement, if no match is met.

Limiting the scope to a balanced opening and closing bracket combos drastically reduces the grammar that needs to be parsed and hence when it can be recognised as an unparsable section.
