### ISSUE TITLE
sqlfluff CLI stdin does not use config

### ISSUE THREAD

**Issue by roivant-matts** [sqlfluff/sqlfluff#3640]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

When providing sqlfluff a file path it properly determines configuration from .sqlfluff files nested in the project. When providing data to be linted as stdin it does check the base config (from where the command is run), but is not using the nested config.

I noticed this behavior when the vscode extension was not using my config but it was working (by file reference) when using from the CLI. Digging into that code base I noticed the extension uses stdin when onType option is selected and file references when onSave is used. 

### Expected Behaviour

I would expect the config behavior to be the same in either file or stdin mode.

### Observed Behaviour

See this repo for test: https://github.com/roivant-matts/sqlfluff_test

base config only test no issues detected
```
➜  base_config_only git:(main) sqlfluff lint --format json bigquery_templates/test.sql --ignore parsing
[]
➜  base_config_only git:(main) cat bigquery_templates/test.sql | sqlfluff lint --format json - --ignore parsing
[]
```

nested config - the stdin option does not check nested config but is using the base config
```
➜  nested_config git:(main) sqlfluff lint --format json bigquery_templates/test.sql --ignore parsing
[]
➜  nested_config git:(main) cat bigquery_templates/test.sql | sqlfluff lint --format json - --ignore parsing
CRITICAL   [L057] Applying rule L057 threw an Exception: string index out of range
[{"filepath": "stdin", "violations": [{"line_no": 1, "line_pos": 29, "code": "TMP", "description": "Undefined jinja template variable: 'staging_prefix'"}, {"line_no": 1, "line_pos": 49, "code": "TMP", "description": "Undefined jinja template variable: 'bucket_table_name'"}]}]
```

### How to reproduce

See observed behavior and test repo:
See this repo for test: https://github.com/roivant-matts/sqlfluff_test

### Dialect

bigquery

### Version

1.2.1

### Configuration

see test repo above

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by barrywhart** [comment]
Are you requesting that in the second example (stdin), SQLFluff should look at `bigquery_templates/.sqlfluff`? I don't see how that's possible. SQLFluff has no way of knowing where the contents of stdin are coming from. It's the shell (bash) that's reading from `bigquery_templates/test.sql` and passing that through a pipe to SQLFluff.

Can you clarify if this is what you're asking, and if so, convince us that it's technically feasible?

**Comment by roivant-matts** [comment]
It relates also to the vscode extension or I'd imagine any integration to an IDE where the nesting config is expected and stdin is required for performance. I am not sure why the extension author chose stdin when linting on typing, but I assume performance or some other issue. It is the default option which basically causes nested config to fail (I understand it's a separate project).

The way I can imagine it working is to check for nesting config from the working directory where executed. Or an option to specify a base directory from which to look for configuration with the nesting logic. I think there is a config option but it just takes one file.

Actually how does nesting config work when a file is specified with a full path provided? How does it get the base config etc if it's not in the same dir but a higher level one?

Thanks for response, really cool tool!

**Comment by barrywhart** [comment]
This sounds like out might be more appropriate as an issue against the VSCode extension. Changing SQLFluff to support another tool using it in a strange way seems backwards to me.

BTW, there's an open PR right now for the VSCode extension to get it working again after being broken for months. If you're a user, you may want to test it.

Please check the SQLFluff docs re: nested config. I think behavior is described there.

**Comment by barrywhart** [comment]
There's an existing command-line option `--config <extra_config_path>`. I wonder if that would help.

Overall, I still believe that this should be addressed somehow in the plugin. Even if we changed SQLFluff, the plugin would have to be updated to take advantage of that change.

**Comment by tunetheweb** [comment]
I agree it sounds like it belongs as an issue in the other repo.

I also believe it sounds like something that should be supported. If a SQL file is in a folder with a separate `.sqlfluff` config file, then that's the config should be used to lint that file. Perhaps the current extension authors all have a top level `.sqlfluff` config file and didn't consider this scenario?

But for SQLFluff itself I think it makes less sense (plus I agree with @barrywhart that I'm not sure how you'd even go about doing this technically since SQLFluff doesn't actually know where the file lives by the time it gets to it since it's not a file as far as it's concerned!).

So, could you summarise this issue in a new issue in https://github.com/sqlfluff/vscode-sqlfluff repo? Although it's party of the whole sqlfluff repo, it's managed by different people.

**Comment by barrywhart** [comment]
Yes, there's probably an important use case here. We should look and see what `--config <extra_config_path>` does. I doubt it does what's being requested, but it's related functionality that could perhaps be extended (or at least should be considered during design, in order to avoid weird interactions or conflicts).

**Comment by tunetheweb** [comment]
Annoyingly I don't think that will work for two reasons:

1. We made a design decision that `--config` was an override, not an addition when it was implemented 😔 So it's `--config <config-path>` rather than `--config <extra_config_path>`.
3. Even without that, you'd in theory need to pass every path up until the top level project as opened by VS Code. So could get tricky.

**Comment by tunetheweb** [comment]
FYI discussion on whether `--config` should override or be in addition is here if interested: https://github.com/sqlfluff/sqlfluff/issues/1244#issuecomment-977952084

**Comment by roivant-matts** [comment]
The extra config path option seems to only take one file (no nesting). Sounds good for me to try the PR. At least I found the on save option is working, so it's functional. After thinking about it, I see the challenge. The stdin would probably need to take both the stdin and a config option of the target file path (just used for nesting config only and ignored for content).

Anyway, all good for me and thanks again. Makes sense to close the issue.
