### ISSUE TITLE
"sqlfluff fix": Questionable reformatting of long line

### ISSUE THREAD

**Issue by barrywhart** [sqlfluff/sqlfluff#365]
I'm testing `sqlfluff fix --rules L001,L003,L006,L008,L010,L011,L016,L018,L019,L022,L023,L030` on some of our projects.

This was a case where the reformatting seemed a bit ugly, and maybe there's a better way.

Given this original line as input (part of a `WHERE` clause:
```
recommendation_list[ORDINAL(1)] = 'uses_small_subject_line' AND uses_small_subject_line != CAST(effect_size_list[ORDINAL(1)] AS FLOAT64)
```

It got reformatted as:
```
    recommendation_list[
            ORDINAL(1)
    ] = 'uses_small_subject_line' AND uses_small_subject_line != CAST(
            effect_size_list[ORDINAL(1)] AS FLOAT64
    )
```

I think splitting the lines around the `AND` would be much more readable, something like:
```
recommendation_list[ORDINAL(1)] = 'uses_small_subject_line' AND
    uses_small_subject_line != CAST(effect_size_list[ORDINAL(1)] AS FLOAT64)
```

I didn't have a max line length set, so I assume it was using the default.

If you like, let me know and I can provide a full example query. I'm just doing initial triage right now...

**Comment by alanmcruickshank** [comment]
No need to provide the rest of the query here, I think I can see what's going on.

The logic about *where* to put line breaks when reformatting.

I think the ideal scenario here is:
```
recommendation_list[ORDINAL(1)] = 'uses_small_subject_line'
    AND uses_small_subject_line != CAST(effect_size_list[ORDINAL(1)] AS FLOAT64)
```
(because I think it currently prefers operators at the start of lines rather than the ends)

The next shortest case should probably be:
```
recommendation_list[ORDINAL(1)] = 'uses_small_subject_line'
    AND uses_small_subject_line != CAST(
        effect_size_list[ORDINAL(1)] AS FLOAT64
    )
```

Beyond that it will probably start to behave a little strangely.... That might be the sensible point to allow it to split the brackets.

**Comment by barrywhart** [comment]
Thinking a bit about this. When splitting a line, it seems like two criteria are:
* Depth of the parse tree: Prefer splitting lines "higher" in the tree
* Maybe also consider the operators: For example, as you say, square brackets belong together if practical

My first intuition is that bullet 1 is the "main" criteria, but the second can serve as a tiebreaker.

Line splitting is an interesting problem -- definitely more subtle than indentation, because it has to manage potentially conflicting constraints.

**Comment by joellabes** [comment]
I just ran into a very similar issue. I have a line:
```
startdate < date_trunc('day', getdate()) and enddate >= date_trunc('day', getdate()) as is_currently_active
```
which `sqlfluff fix` changed to 
```
startdate < date_trunc(
            'day', getdate()
        ) and enddate >= date_trunc('day', getdate()) as is_currently_active
```

If I was fixing this manually, I would have changed it to 
```
    startdate < date_trunc('day', getdate()) 
        and enddate >= date_trunc('day', getdate()) 
        as is_currently_active
```
but that then falls afoul of `L003 Indentation not consistent with line #12`. (If you'd like, I can also create a separate issue for that)

**Comment by alanmcruickshank** [comment]
Thanks for the extra intel @joellabes . I think your assessment of what *should ideally* happen is spot on.

The current reflow logic looks for potential indent points within the existing parse structure. At the moment we don't inject any around operators like `and` or `<`. To address this properly would probably need a bit of a rethink of the parsing of expressions, at the very least to distinguish here between `and` and `<` so that we take operator precedence into account.


This will need some legwork to do.

**Comment by barrywhart** [comment]
@NiallRees, @alanmcruickshank: This is the rule we were discussing in the meeting.
