### ISSUE TITLE
Large File Size Causes Extremely Long Runtimes

### ISSUE THREAD

**Issue by cpendery** [sqlfluff/sqlfluff#3838]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

sqlfluff takes ~10 minutes to lint a single SQL file. Discovered by @ahmedalishaikh

### Expected Behaviour

I'd expect its linting to take a few seconds, like it does when the file is smaller

### Observed Behaviour

When the file size grows, the time to lint grows per line exponentially. A file with 1 line of this data is almost instant, but just pasting it in multiple times increases the runtime per line dramatically. Large files are basically un-lintable

### How to reproduce

Create a SQL file with 1.1k lines containing the following query into a file `s.sql`
```sql
insert into table_1 (field_1, field_2, field_3, field_4, field_5, field_6) values ('value_0', NULL, 2, 'value_3', 4, 5);
```
Run the following command
```shell
sqlfluff lint s.sql 
```

### Dialect

N/A

### Version

```shell
> sqlfluff --version
sqlfluff, version 0.9.1
```

### Configuration

N/A

### Are you willing to work on and submit a PR to address the issue?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by fmms** [comment]
There have been multiple performance improvements in the last months . Please upstate to version 1.3.1.

**Comment by cpendery** [comment]
@fmms The issue persists when running using `1.3.1` as has an even longer runtime. I had to enable `large_file_skip_byte_limit=0` as `sqlfluff` gave a warning about byte size causing a parser lock. Would this be the issue & what is the parser lock that its referring to?

**Comment by alanmcruickshank** [comment]
With the byte limit - it should _skip_ the file and not lock on it. Can you try setting `large_file_skip_byte_limit` to something really low and see whether you're still getting locking issues? If you are, that's a bug. You'll likely get a lot of warnings as it skips all the big files but it should at least remain responsive.

**Comment by cpendery** [comment]
I need to lint the file, so changing the limit such that it gets skipped won't work for me. Is there some previous art I can look at for why the avoiding large file sizes got added / what locking is occuring so I can understand better what's happening? @alanmcruickshank

**Comment by alanmcruickshank** [comment]
It's primarily the _parsing_ step rather than any others which takes the most time. To confirm this, you should be able to see the same slowdown when running `sqlfluff parse` on the same file (which skips the lining step).

If you take a look at issues tagged with *performance* then you'll see some of the next planned work to make things faster. You can run `sqlfluff parse -vvvvvvv` to see the detailed logs of how the parser is handling the file to debug what might be taking a long time.

**Comment by alanmcruickshank** [comment]
@cpendery - there's been significant performance work over the last few months. While there's probably still some headroom, I'm going to propose that we close this issue for now. Large files will still take more time than short files, but we've had a roughly 100x improvement in parsing since early 2023. Check out https://designingoverload.com/sqlfluff-performance/ for details.

I expect we'll have some more gains to come in performance in the future, but the focus will shift back onto features for a while I expect.
