### ISSUE TITLE
Reorganize rule names

### ISSUE THREAD

**Issue by pwildenhain** [sqlfluff/sqlfluff#4031]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### Description

Let's think about a nice way to rename rules/codes, so that we don't have to look up what the rule code is everytime we think about them 😵 

Here's an example of what `pylint` messages look like:

```sh
$ pylint etl.py 
************* Module etl
etl.py:20:61: C0303: Trailing whitespace (trailing-whitespace)
etl.py:1:0: C0114: Missing module docstring (missing-module-docstring)
etl.py:7:0: W0622: Redefining built-in 'compile' (redefined-builtin)
etl.py:7:0: E0401: Unable to import 'parse' (import-error)

------------------------------------------------------------------
Your code has been rated at 5.56/10 (previous run: 9.95/10, -4.40)
```

You can see that the have "common sense" names as the end of each linting message.

Here's an example of what the current output looks like for `sqlfluff lint`:

```sh
$ sqlfluff lint models/output/
=== [dbt templater] Sorting Nodes...                                                       
=== [dbt templater] Compiling dbt project...                                               
=== [dbt templater] Project Compiled.                                                      
== [models/output/redcap_import.sql] FAIL                                                  
L:   6 | P:   5 | L019 | Found leading comma. Expected only trailing.                      
L:   6 | P:   6 | L008 | Commas should be followed by a single whitespace unless
                       | followed by a comment.
L:   9 | P:  40 | L012 | Implicit/explicit aliasing of columns.
L:  17 | P:   6 | L003 | Expected 1 indentations, found 1 [compared to line 16]
```

For the record I think on the whole, our output is better organized/nicer to look at than pylint. But I think it would be greatly improved if we could implement common sense names like this:

```sh
$ sqlfluff lint models/output/
=== [dbt templater] Sorting Nodes...                                                       
=== [dbt templater] Compiling dbt project...                                               
=== [dbt templater] Project Compiled.                                                      
== [models/output/redcap_import.sql] FAIL                                                  
L:   6 | P:   5 | L019 | Found leading comma. Expected only trailing. (wrong-comma-style)                  
L:   6 | P:   6 | L008 | Commas should be followed by a single whitespace unless
                       | followed by a comment. (comma-missing-whitespace)
L:   9 | P:  40 | L012 | Implicit/explicit aliasing of columns. (wrong-column-alias-style)
L:  17 | P:   6 | L003 | Expected 1 indentations, found 1 [compared to line 16] (unmatched-indentation)
```

With this change, I could ideally also disable/enable rules according to their readable names and/or their codes, such as 

```sql
select
  field_1,
field_2, --noqa: unmatched-indentation
from my_table
```

You'll also notice from the above example that pylint codes have different prefixes (`W0622`, `E0401`, etc)

Here's their [definitions](https://github.com/PyCQA/pylint/blob/a57edea63fa7a1edfcb63074f9e2a373ebabb7cd/pylint/constants.py#L34-L41) for those, but basically `E = Error`, `W = Warning`, `R = Refactor`, `C = Convention`

And this brings us to the second part of this issue: what the codes should be. I think we can follow `pylint`'s example, and break up the rules into categories. Here are a few to start: 

`R = readability`
- Operators should follow a standard for being before/after newlines (L007 --> R001)
- Inconsistent capitalisation of keywords (L010 --> R002)

`C = Convention` (AKA Best Practices)
- Implicit/explicit aliasing of table (L011 --> C002)
- Table aliases should be unique within each clause (L020 --> C002)
- Trailing commas within select clause. (L038 --> C002)

`W = Whitespace`
- Indentation not consistent with previous lines (L003 --> W001)
- Operators should be surrounded by a single whitespace (L006 --> W002)

`D = dialect specific`
- SP_ prefix should not be used for user-defined stored procedures in T-SQL. (L056 --> D001)

### Use case

- [ ] Give all the rules "symbolic" names or "short" names
- [ ] Include these in the lint messages
- [ ] Allow these to be disabled in the config by short name and/or rule code
- [ ] Consider if rules should be disabled by default (I'm looking at you `L052`. And yes I'm not going to say what rule that is here in order to prove a point on why this is an important change to make 😜 )
- [ ] Should we more tightly integrate these will rule groups? Should these replace rule groups, and all just become implicit rule groups?

### Dialect

All

### Are you willing to work on and submit a PR to address the issue?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by alanmcruickshank** [comment]
I like this as a suggestion. Thanks for writing this up. I think I'm on board with the rough direction.

The modifications I'm considering would be:
1. Is the CLI output confusing, or should we put the short names on a new line, or at the start of the line? On reflection I'm thinking maybe your proposed output is actually clearer - but I'm still not totally sure yet 🤔 .
2. Is there a 1:1 mapping between rule _codes_, rule _names_ and types of issue? For example, the way that L003 is going with the reflow code is that it might have many features. From an execution point of view, I think that makes sense - but for a user, do you think they might want to refer to different bits of it separately? This might not always be possible (e.g. we can't indent a line until there are line breaks in a sensible place), but in some cases it might: e.g. capitalisation of various things could be one rule, with many names.
3. I think rule groups _do still exist_, at the very least because there will likely be a default _format_ set for `sqlfluff format`.
4. Assuming we go down this road, I could imagine quite a powerful selector syntax which overlaps groups, codes and names e.g. `core+R-R001,C044` - is that a good thing or does that make things more complicated?

**Comment by pwildenhain** [comment]
> Is the CLI output confusing, or should we put the short names on a new line, or at the start of the line? On reflection I'm thinking maybe your proposed output is actually clearer - but I'm still not totally sure yet 🤔 .

Right now, I like how everything is aligned in our CLI output, as opposed to the `pylint` output

> Is there a 1:1 mapping between rule codes, rule names and types of issue? For example, the way that L003 is going with the reflow code is that it might have many features. From an execution point of view, I think that makes sense - but for a user, do you think they might want to refer to different bits of it separately? This might not always be possible (e.g. we can't indent a line until there are line breaks in a sensible place), but in some cases it might: e.g. capitalisation of various things could be one rule, with many names.

I think it's totally fine if L003 gobbles up a few of the current rules, and makes it more restrictive for the user. I doubt anyone actually wants to disable everything that L003 is going to do, if anything they can just set very lax config values as workarounds as they try to improve their codebase (like a very long line length for instance)

> Assuming we go down this road, I could imagine quite a powerful selector syntax which overlaps groups, codes and names e.g. core+R-R001,C044 - is that a good thing or does that make things more complicated?

I think as long as we have a recommended way in the documentation, then more flexibility is generally a good thing. However, if it's a pain for us as maintainers to support all these different methods, then we can place some tighter restrictions. It is `2.0.0` after all!

Another question for you -- do we continue to support the old `LXXX` syntax in the 2.0.0 release? If so, for how long? Or do we just do a clean break from it? We can just spit out a warning that there are unused config values, it doesn't have to stop the linting from actually running (the same way if I has `--noqa: L100` in the code.

**Comment by tunetheweb** [comment]
> Another question for you -- do we continue to support the old `LXXX` syntax in the 2.0.0 release? If so, for how long? Or do we just do a clean break from it? We can just spit out a warning that there are unused config values, it doesn't have to stop the linting from actually running (the same way if I has `--noqa: L100` in the code.

A lot of linters (pylint included?) support both. I don't see why we wouldn't do the same? Maybe for 3.0.0 we drop the older ones, but I wouldn't for 2.0.0 - that would be quite a big change IMHO.

**Comment by pwildenhain** [comment]
> Is it worthwhile to consider Warning rules?

Totally, I thought about that too. 
I think a case could easily be made for combining whitespace and readability into just "readability", and commandeer the W for "Warning"

What kind of rules would you put there? I think #2 and #3 rules that I have under "convention", could go under "warning", as in "Hey your code might be wrong/is unstable"

**Comment by alanmcruickshank** [comment]
I'm tempted to handle warnings separately (although they're now supported as part of #4053). This is much more about categorisation, that how strict people want to be.

I've been thinking about dialect specfic rules, and things that might potentially be templater specific (like some of the dbt rules):

_should we require that dialect specific rules are plugins?_

I could imagine bundling some dbt specific rules in with the dbt templater, or allowing a bundle of tsql specific rules to likewise be installable as a plugin. If we did that, then they don't clutter the namespace for people who don't need them.

If we like that idea - it does hint maybe at dropping _codes_ as the primary identifier at some point. Some rules can expose them if they want - but we're not going to be able to coordinate codes across all packages. I'm wondering whether a more _namespaced_ approach might work, kind of like `layout.indent`, `layout.spacing`, `dbt.refs` or `format.capitalisation.keywords`.

For backward compatibility I do think it makes sense to provide a mapping for the old codes to the new names - but there's no requirement for _any new rules_ to support codes at all. Likewise it then makes it easy for users to select either `layout` and get all the layout rules or `format.capitalisation` and get all the capitalisation rules etc...

**Comment by noel** [comment]
All that makes sense and dbt specific rules do seem like they belong in the templater.

> there's no requirement for any new rules

Why do you feel this way vs always having a code even if new?
 
The original example has both
`C0303: Trailing whitespace (trailing-whitespace)`

I do like the idea of potentially configuring rules like
```
layout.all
format.capitalisation.all
```
Is that what you are thinking?

If we had codes like:
```
RFMT001
RLYT004
```

We would have the convenience of a shorter name to exclude something with some semantic meaning.

In the end either would work, but we may want to consider either no codes or always codes, it might be more confusing if this is inconsistent.

**Comment by pwildenhain** [comment]
> In the end either would work, but we may want to consider either no codes or always codes, it might be more confusing if this is inconsistent.

I can 💯 get behind the idea of no codes. If they're just an extra  layer of organization that serve no purpose other than to make us feel like things are organized, we shouldn't indulge that.

If we really want to start defining rule groups, then I vote for using the existing "group" infrastructure 

I'm also 💯 behind the idea of templater specific and dialect specific rules needing to live in plugins. That feels a lot cleaner

**Comment by alanmcruickshank** [comment]
As far as implementation goes, I'm thinking that we need to break the 1:1 link between implementation and a "rule".

Something like:
- We have "linting plugins" or "rule plugins" or something, which act as _implementations_ of rules. They declare which "rules" they support.
- When someone selects (or excludes) rules, they're effectively running a selection query against this list of available rules.
- Once we know which rule engines to run, they run and return appropriate fixes given the selection.

**Comment by alanmcruickshank** [comment]
....and going even further:

_Should every "rulepack" be a plugin?_

That would mean:
1. All rules are defined within a `RulePack`. This is a pluggable module and would work with the existing plugin architecture. We would still support the legacy plugin method for individual rules, and they would just be registered under a `default` or `custom` `RulePack`.
2. The `RulePack` declares which rules it offers and also presents a selection interface. If a user passess `layout.indent` selector to `sqlfluff.lint` then all plugins are queried to see if they offer that rule, only the `layout` plugin would respond and then it is called with the selector `layout.indent`. `layout` might also define `layout.spacing`, but the choice of how to execute given only a subset of issues are wanted us up to the `RulePack` itself - that provides a performant option for execution in situations where one scan through the file is enough to yield several different issues.

**Comment by alanmcruickshank** [comment]
I've started fleshing out where I think all the rules would go, rule by rule and I think I've classified all of the easy ones: https://docs.google.com/spreadsheets/d/1xGig5Eq0vTdc7d82wwTXSD4X1BUmk1zgiMUuoVPRfaU

(doc should be viewable to anyone with link- but let's keep the conversation here in the thread).

**Comment by alanmcruickshank** [comment]
> We would have the convenience of a shorter name to exclude something with some semantic meaning.

I like this idea @noel - and I'm almost wondering whether the codes end up being the most specific thing someone can reference and the "name" might actually be a little more generic in some cases...

**Comment by pwildenhain** [comment]
I took a look at the doc, it's well organized

At first I was turned off by the idea about just having `layout.spacing` bundle a bunch of rules, but the more I try to come up with a rebuttal the more convinced I am that this is a good idea 😂

People can still exclude specific codes if they want, but in my experience, people want to disable whole _categories_, like capitlisation for instance.

I think having rules be part of these groups is smart, allowing us to keep the rule symbolic names easier for people to remember, when they want to disable it (like `layout.spacing`). But still having the ability to house different rules in these groups that may have very niche uses cases.

Also, I think the "implicit/explicit aliasing" rules should go under and "alias" group: `alias.table`, `alias.column`, etc

**Comment by alanmcruickshank** [comment]
@pwildenhain - jotting down my thoughts on practically how we might do this.

I think the key points are:
- To maintain backward compatibility, I think considering this as an evolution of the existing `BaseRule` class makes sense. Most of what we need is already there and I don't think we need to totally re-engineer things to achieve this.

So specifically:
- [ ] The `_eval()` method of the existing `BaseRule` should allow (in addition to single `LintResult` and lists of the same) rules to return a `dict` of `LintResult` where the keys are the fully qualified rule names for the result that they return (a variant of this would be to key the results on the new rule _code_ - that would be more concise for rule developers but slightly harder to read).
- [ ] `BaseRule` classes can operate in two _declaration_ modes. The old style is where the class name its self encodes the rule _code_. The new style allows a single rule to declare multiple rule names or rule codes - this would be on a class attribute (called `declared_rules`), allowing a `tuple` of `DeclaredRule` objects (probably a `namedtuple` type), which declares the fully qualified names, codes, groups and any aliases (which would include the old rule code if applicable). If a rule declares itself in the new style - the `_eval()` method must also accept a `selected_rules` argument, which is a list of fully qualified names (or codes if we decide to do that above), which the rule can then use to subselect rules. Rule _no not_ have to do their own filtering (in particular where it makes no different to the execution path), as the `BaseRule` should do a filter on any returned results. If a rule defines multiple rules - _it MUST return it's results as a `dict` so that the `BaseRule` knows how to attribute them_.
- [ ] We should aim for rules which are defined together to have namespaced names (e.g. `layout.spacing`) so that whole rules can be turned on or off by using the namespace name - but _I don't think we should check or enforce this_. If multiple `BaseRule` objects share the same namespace, or a single `BaseRule` defines rules in multiple namespaces - I think this is ok. We cand handle this complexity in the rule selector resolution.
- [ ] The `BaseRule` class must present a `.declare_rules()` method to allow the `Linter` to know what rules are available and what rules it may select from a given `BaseRule`. This should power the `sqlfluff rules` CLI command.
- [ ] The `Linter` must be able to take the declared rules of all installed base rules - and resolve the user provided rule selector strings (which may use a mixture of qualified names, codes or aliases) to generate a desired list of fully qualified rule names (@pwildenhain - this is the bit I DM'd you about). The existing `rules` and `exclude_rules` configuration arguments are probably too rudimentary for this more flexible approach and so we probably need a new approach for this for it to remain manageable. We should make sure this works with multiple potentially nested configuration files and the need to be able to resolve a stack of multiple selector strings.
- [ ] The CLI output needs to be modified to display the new rule names/codes appropriately (lots of suggestions on how to do this well in the thread above).

I like the idea of moving more of these rules into plugins, but I don't think that _necessary_ for the reorganisation - and in particular we shouldn't move _all_ of the rules to plugins, because the `core` test suite relies of a few always being present and they should remain part of the main library. I suggest any _pluginisation_ happens as a seperate job _after_ the bulk of this issue is resolved.

**Comment by pwildenhain** [comment]
Been looking at the code today and getting some initial thoughts down

New selection syntax should support
- Rule codes (LS001)
- Old rule codes (L001)
- Rule names (layout.spacing)
- Rule namespaces (layout) 
- Rule groups (core, format)

And it should support nested configs, meaning if we have a `.sqlfluff` file in the project root AND in one of the child directories, then we carry over selected rules from the root directory and further include/exclude rules based off configuration in the child directory.

On a separate note, I don't think that nesting `rules`/`exclude_rules` in the `.sqlfluff` currently works super well -- though I might be approaching it the wrong way. I can talk more about this at the next maintainers meeting

Here's one potential approach:

We'll still keep `rules` and `exclude_rules` config values.

We support comma separated selection/exclusion e.g. `core,LB005`, `layout,captilasation.literals`

Before any filtering is done, the selection input is expanded into a list of rule names e.g. `"layout.spacing,L009"` --> `[LS001,LS002,LS003,LB001]`

It then replaces any selection configuration that came before it (nested configs)

Now we have our final `rules` selection

Follow the same process for `exclude_rules` (including exclusion configuration that comes before it)

Then filter the rules being included against the rules being excluded, and you have your rules to run for a given file(s).

I think in order to do proper expansion from criteria to individual rules we'll need to collect some sort of rule metadata at the beginning of linting that we can reference while doing the selection (similar to how `dbt` looks at the `manifest.json` to help with model selection). It might even be smart to follow their lead include a manifest when `sqfluff` is installed that has all this metadata. We could auto-generate it whenever rules are added/re-categorized, and include it as an asset in the package.

Lastly, with this approach it would no longer allow as much fine tuning. For example, under this proposal if someone only wants to run `L005`, it's going to be re-mapped to `LS001` which actually includes `L001,L005,L006,L008,L015,L017,L023,L024,L039,L048,L050`. I think this is actually a big improvement, though it is a breaking change. But if someone only wants `L005` and not all these other rules, they'll be disappointed

I know this was a little rambly, but I'm happy to take any feedback
