### ISSUE TITLE
duckdb dialect

### ISSUE THREAD

**Issue by davetapley** [sqlfluff/sqlfluff#4115]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### Description

duckdb is [Postgres](https://duckdb.org/docs/sql/introduction) but [with some extra syntax](https://duckdb.org/2022/05/04/friendlier-sql.html)

### Dialect

duckdb

### Are you willing to work on and submit a PR to address the issue?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by greg-finley** [comment]
Nice, I keep hearing good things about duckdb, so no doubt it would be useful to add.

Here's a similar PR to add a different dialect that could be a good starting point (sounds like we should extend from Postgres instead of ANSI): https://github.com/sqlfluff/sqlfluff/pull/3312 . I would suggest just add a single feature (or as many as it's easy to do together) and raise further issues for other features. It doesn't have to be perfect / complete right away.

**Comment by holdenmatt** [comment]
Hi, great to see DuckDB added as a dialect!

I started testing it and noticed a couple of issues:

1. `select * exclude` and `select * replace` work, but not `select *`

2. Querying from a remote URL doesn't parse, such as this example:
`SELECT count(*) FROM 'https://shell.duckdb.org/data/tpch/0_01/parquet/customer.parquet'`

Apart from these, seems to be working great so far!

Should I file a separate issue to track these?

**Comment by greg-finley** [comment]
Yep, please file separate issues for each item. Thanks for reporting!
