### ISSUE TITLE
Option to incrementally save file during "fix"

### ISSUE THREAD

**Issue by aaronsteers** [sqlfluff/sqlfluff#427]
I'm doing a one-time cleanup of a fairly large repo (200+ sql files). The process is taking a long time. I am watching #368 and I totally understand why it's going to be slow for a large and unkempt repo. I wanted to ask though, since it seems to be holding all edits until the end, is there any plan to save each file, one at a time, rather than waiting until all files are processed?

The nightmare scenario is that file number 199 of 200 has a fatal error and the whole thing is aborted before getting serialized back to disk. (More realistically, I might want to cancel the long running operation to tweak my rules and restart without losing all the progress.)

Thoughts?

**Comment by alanmcruickshank** [comment]
Interesting. I hadn't thought of this, but yes something might be possible.

In particular, at the moment we first *lint* all the files, then present the user with a list of fixable errors, which are then applied individually. If during that second phase there was a bad error, then all of the files up to that point would have been saved, but I can imagine that during the *first* phase, it could be tedious waiting for all of the files.

What might be more useful would be to have to the option to fix each file individually. i.e. rather than linting *all* the files to start with, it lints each file and then if any errors are found, present the user with the option of fixing them *before* moving on to the next file.

I can see two routes to actually doing this:
- make `lint_paths` into a generator which either slowly builds up a `LintingResult` as per now, or there is the option of dealing with them individually in the logic of the `fix` command in `commands.py`.
- bring the fix logic into the `LintingResult` object, and then make it optionally run on `LintingResult.add()` which is already called within `lint_paths`.

From a purely organisational route, I like the sound of the latter the most, but I'm not sure how to elegantly handle the user input part of it outside of the `fix` function without things getting really convolted.

@aaronsteers , would you like to have a try at adding this feature?

**Comment by NiallRees** [comment]
I believe this to be indirectly solved by #541, so closing!
