### ISSUE TITLE
Snowflake Redundant Space `For QUALIFY` and `ROW_NUMBER OVER` Analytical Functions

### ISSUE THREAD

**Issue by murat-cetinkaya** [sqlfluff/sqlfluff#4573]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

Sqlfluff adds redundant spaces to some SQL analytical functions in Snowflake code.

### Expected Behaviour

I expected:

`QUALIFY(someFunction)`
`ROW_NUMBER OVER(someColumn)`

### Observed Behaviour

I observed:

`QUALIFY (someFunction)` 
`ROW_NUMBER OVER (someColumn)`

with a redundant space between function names and parentheses. 

### How to reproduce

Just write a SQL query using `QUALIFY()` or `ROW_NUMBER OVER()` functions.

### Dialect

Snowflake

### Version

2.0.1

### Configuration

-- here's my .sqlfluff config file content. The rest of the configuration uses defaults.

[sqlfluff]
templater = jinja
dialect = snowflake
ignore = templating

rules = layout.spacing

[sqlfluff:templater:jinja]
load_macros_from_path = macros

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by alanmcruickshank** [comment]
The current behaviour is in line with the snowflake docs:
- `OVER`: https://docs.snowflake.com/en/sql-reference/functions-analytic#examples
- `QUALIFY`: https://docs.snowflake.com/en/sql-reference/constructs/qualify

In both cases, it is assumed that there **is** whitespace between the keyword and the bracketed expression. I believe this is because `OVER` and `QUALIFY` aren't functions.

As an aside, `QUALIFY` shouldn't need brackets at all, you should just be able to write `QUALIFY someFunction`.

The [existing layout configuration](https://docs.sqlfluff.com/en/stable/layout.html#configuring-layout) does allow for customisation of layout, but not currently by _keyword_, only by _dialect element_. I do want to work on that capability, but it's not currently high on the roadmap.

Are you aware of a public style guide which does encourage treating them like functions? If so, that would help prioritise this.

**Comment by murat-cetinkaya** [comment]
@alanmcruickshank Thank you for the detailed explanation. You're rigth, these are not bugs according to Snowflake documentation (interestingly). I'll close the issue.
