### ISSUE TITLE
Linter very slow on large (SQL) codebases

### ISSUE THREAD

**Issue by mrshu** [sqlfluff/sqlfluff#474]
First of, huge props for pushing `sqlfluff` forward @alanmcruickshank! It's been quite a bit since I saw the new developments last time and it seems like it's a whole different (and likely way more powerful) thing now. 

We've been using a very old but stable version `0.0.7` in our CI at Slido.com for the better part of the year and it has served us very well. I'll create a PR to describe that at https://docs.sqlfluff.com/en/latest/inthewild.html and will probably write up our experiences at our [tech blog](https://medium.com/slido-dev-blog) as well.

That said, when I tried the newest released version (0.3.6) on part of our (SQL) codebase, it took nearly 11 minutes to finish. Granted, it's 19810 lines and 98 files in total but still, it's a pretty big difference from the `0.0.x` version of sqlfluff we are using so far. I was therefore wondering whether the new parsing mechanism is known to be a bit slower and this is expected. We can easily work around that by only checking the files which got changed in the CI pipeline -- I just wanted to be sure I didn't do something wrong.

Thanks again!

**Comment by alanmcruickshank** [comment]
Heya @mrshu - thanks for checking out the most recent version!

Yes it is slower. There was a big change in approach since the version which you're on - the old version didn't parse everything and just looked for things that _looked a bit like sql_. That meant it could only pick up a subset of the things I wanted it to.

The newer parser *actually parses the sql*, right down to the individual expressions, which means that it a) more powerful, but b) yes much slower.

That doesn't mean that I'm not keen to speed it up however! I'm sure there are efficiencies to be had in the way that the parser works now - there have been several rounds of improvements already, but as you've noticed - more should be possible.

The next release has a few things that I think should help, but I'll see if I can add some extra debugging features to help use your codebase to drive how we do speedups. In particular I'm wondering whether it's a few very slow files, or just everything taking _a bit too long_.

**Comment by pwildenhain** [comment]
Also @mrshu see #368 for more discussion about performance improvements

**Comment by NiallRees** [comment]
Going to close this for now as I'm not sure it is specifically actionable. We have an existing issue for investigating different parsing options which is pretty much what this existing issue boils down to as the bottleneck: https://github.com/sqlfluff/sqlfluff/issues/595

@sqlfluff/sqlfluff-maintainers please feel free to re-open if you disagree!
