### ISSUE TITLE
Enable more fine-granular silencing of rules

### ISSUE THREAD

**Issue by moertel** [sqlfluff/sqlfluff#4779]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### Description

Introducing more config options to selectively disable rules for particular types or keywords rather than requiring to turn off the rule entirely.

### Use case

This is more of a general question. I have understood that sqlfluff is opinionated. This is cool for teams/projects that are just starting out, but has been a bit of a rough start for someone like me trying to codify an existing set of conventions. **Is this use-case something you'd want to support?** Put another way, would you be open to contributions that allow fine-granular silencing of rules?

The Internet™ might disagree with some of the existing conventions I'm trying to codify. My team still wants to take advantage of automated linting, though. Currently for many convention mismatches, my only choice is turning the rule off entirely. (One notable example being a missing space between `using` and the opening bracket `(`. I can only turn off LT01, not selectively turn it off for the `using` keyword.)

### Dialect

Postgres; but also affects core rules.

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by tunetheweb** [comment]
I don’t think we want to add config codify very specific “bad” practices - e.g. a config to allow `USING(` to exists without a space in between.

However, I think it would potentially be good to have a generic `do_not_enforce_space_before_opening_bracket` config for when code bases are not ready for enforcing this yet. Plus we’ve had a few false positives on this in the past.

@alanmcruickshank is it possible to configure that now? If not do you think we should add it?

Hopefully that specific example also lets you understand the general thought process we have here. Always best to raise an issue with a suggested approach so it can be discussed and/or agreed on rather than going straight to PR.

We do want SQLFluff to be an opinionated, but configurable linter that meets most general use cases. But each config option added makes the configuration even more complex than it already is, and requires maintenance once it’s in the code base.

**Comment by moertel** [comment]
> [...] each config option added makes the configuration even more complex than it already is, and requires maintenance once it’s in the code base.

Absolutely with you there on this one!

It doesn't necessarily have to be coding a specific workaround for a particular rule. I'm definitely open to deep-dive into the workings of the codebase in a way that would allow for more sophisticated "silencing" of rules. Take this completely fictional configuration:

```ini
[sqlfluff]
exclude_rules = layout.spacing[keyword:using], references.special_chars[char:_]
```

My main ask is to silence rules selectively for whatever set of "entities" they're targeting. For spacing it could be the keywords or blocks. For references it could be the set of allow- or deny-listed characters. You already seem to have the categorisation of entities in place (beautifully so, in fact).

This would _also_ address the cases in which people find bugs but still want to leverage the rule overall.

**Comment by moertel** [comment]
FYI, I've sinced moved on from this project since it was impossible to introduce it into our CI without requiring either major changes to all our files, or turning off rules entirely (thus defeating the purpose). I've removed my "Yes I am willing to submit a PR!" checkmark and am now closing this as nobody else seems to have stumled across it.
