### ISSUE TITLE
Adopt black coding style

### ISSUE THREAD

**Issue by pwildenhain** [sqlfluff/sqlfluff#481]
Especially as this project continues to attract new contributors, I think as unified coding style will be helpful.

I've quite enjoyed `black` for the most part, and there is a `flake8` plugin for `black` https://pypi.org/project/flake8-black/
And there is also a `pytest` plugin for black https://pypi.org/project/pytest-black/

Whichever coding style you prefer, I would be up for implementing it. Since it will touch pretty much the *entire* codebase, I would recommend saving it till the _end_ of a release

**Comment by alanmcruickshank** [comment]
I've had a reasonable subset of the flake8 default set for some time, so that I know what we're dealing with, how much does `black` change if we enabled it.

I'm up for adding it, but like you said, I think we should manage how & when it gets implemented based on how drastic the changes are. If we're actually _pretty close_ then I don't think we need to wait for the end of a release. The python version changes PR mean that the next release will be a major  one, and given the other stuff on the roadmap, it might be a bit away at the moment, so it could be valuable to tidy the code *before* we tackle some of the really meaty changes. 🤷

**Comment by pwildenhain** [comment]
Great point, I'll submit a draft PR to demonstrate the noisiness of the change, and then we can decide it it's worth pursuing from there
