### ISSUE TITLE
dbt-core 1.5 & sqlfluff 2.1.0 - processes

### ISSUE THREAD

**Issue by christopherekfeldt** [sqlfluff/sqlfluff#4863]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

We are trying to upgrade dbt-core and dbt-bigquery to 1.5.0 Together with this, we have upgraded sqlfluff to 2.1.0. 

We got a issue connected to processes set to 0 in our .sqlfluff config. This earlier at least would maximize our processes on our computers to parallel run modified models to speed up the process.an

### Expected Behaviour

That sqlfluff lint would work as before. When commenting out "processes = 0" from config we got to the next issue connected to dbt 1.5.0 versioning and references. But I will post it in a new Issue. 

### Observed Behaviour

==== sqlfluff ====
sqlfluff:                2.1.0 python:                 3.8.10
implementation:        cpython verbosity:                   1
dialect:              bigquery templater:                 dbt
dbt:                    =1.5.0
rules:                                all
==== readout ====

effective configured processes:  8
=== [dbt templater] Sorting Nodes...
Process ForkPoolWorker-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/usr/lib/python3.8/multiprocessing/queues.py", line 358, in get
    return _ForkingPickler.loads(res)
TypeError: __init__() missing 2 required positional arguments: 'node_1' and 'node_2'

### How to reproduce

We run everything in a poetry virtual environment. Command used:

poetry run sqlfluff lint models/harmlay/matm/harm_matm__shipment_stop.sql

### Dialect

bigquery

### Version

sqlfluff : 2.1.0
python: 3.8.10
dbt-core: 1.5.0
dbt-bigquery: 1.5.0
templater = dbt
sqlfluff-templater-dbt: 2.1.0

#
# Packages that are available to all bica-dbt-projects
#
packages:
  - package: dbt-labs/dbt_utils
    version: 1.1.0

  - package: dbt-labs/codegen
    version: 0.9.0

  - package: elementary-data/elementary
    version: 0.7.6

  - package: calogica/dbt_expectations
    version: 0.8.5

### Configuration

[sqlfluff]
templater = dbt
dialect = bigquery
verbose = 1
encoding = utf-8
large_file_skip_byte_limit = 35000
ignore_templated_areas = true
processes = 0
exclude_rules = CP02,LT02,LT05,RF02,CV03,ST05,ST06,ST07

[sqlfluff:indentation]
tab_space_size = 4
indent_unit = space
indented_on_contents = false
indented_joins = false
indented_using_on = true
allow_implicit_indents = true

[sqlfluff:layout:type:comma]
spacing_before = touch
line_position = trailing

[sqlfluff:rules:capitalisation.keywords]
capitalisation_policy = lower

[sqlfluff:rules:capitalisation.functions]
extended_capitalisation_policy = lower

[sqlfluff:rules:capitalisation.literals]
capitalisation_policy = lower

[sqlfluff:rules:references.keywords]
ignore_words = week,month,quarter,year,day,date,function,hour,account,safe,name,type

[sqlfluff:rules:references.special_chars]
allow_space_in_identifier = True

[sqlfluff:templater:dbt]
project_dir = .
profiles_dir = .
profile = etlapp
target = tcm

[sqlfluff:templater:jinja]
apply_dbt_builtins = true

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by brettwatkins-Built** [comment]
I am also seeing this same issue

**Comment by alanmcruickshank** [comment]
There isn't a fix to this in the imminent release but I'll take a look at this one next.

**Comment by alanmcruickshank** [comment]
@brettwatkins-Built @christopherekfeldt - I'm having real trouble recreating this issue.

I don't have access to a live bigquery project which means I'm testing with `dbt-snowflake` rather than `dbt-bigquery`, but I don't see why that should make a difference.

My test setup is with:
python 3.8.10 (as above)
dbt 1.5.0 (as above)
sqlfluff 2.1.0 (and also tested with the latest 2.1.2)
templater: dbt
verbosity: 1

Could either of you confirm whether this issue is still present in the 2.1.2 release (just out) which solves the other issues you mentioned?

If it **does** still occur on that release, it also looks like this might be an upstream python issue, can you post your full `pip list` output to see whether there's something else in there that might be the culprit?

**Comment by sziolko** [comment]
@alanmcruickshank I am in the process of testing upgrading dbt to 1.5 and sqlfluff to the latest (2.1.2) and am seeing this in our CI/CD process that runs sqlfluff. I am seeing it in both python 3.9.17 (what we have had our CI system on) and python 3.11.4 

In my local environment (mac os) I do not see this where I am getting the same output is on an ubuntu image with python installed (https://gitlab.com/python-devs/ci-images), specifically we use the `versionNumber-slim` images for CI. We use pipenv to manage the virtual environment so the CI machine should have a similar set of packages. 

.sqlfluff config was set with `processes = -1` rather than the `0` noted above, so it is potentially any amount of parallelization.

Test setup:
Python 3.9.17 & 3.11.4
dbt-core 1.5.2
dbt-redshift 1.5.8
sqlfluff 2.1.2
sqlfluff-templater-dbt 2.1.2
pipenv 2023.7.11

Full `pip list` output:
```
Package                   Version
------------------------- --------
agate                     1.7.0
annotated-types           0.5.0
appdirs                   1.4.4
asn1crypto                1.5.1
attrs                     23.1.0
Babel                     2.12.1
beautifulsoup4            4.12.2
boto3                     1.26.165
botocore                  1.29.165
certifi                   2023.5.7
cffi                      1.15.1
chardet                   5.1.0
charset-normalizer        3.2.0
click                     8.1.5
colorama                  0.4.6
dbt-core                  1.5.2
dbt-extractor             0.4.1
dbt-postgres              1.5.2
dbt-redshift              1.5.8
diff-cover                7.6.1
future                    0.18.3
hologram                  0.0.16
idna                      3.4
iniconfig                 2.0.0
isodate                   0.6.1
Jinja2                    3.1.2
jinja2-simple-tags        0.5.0
jmespath                  1.0.1
jsonschema                4.18.3
jsonschema-specifications 2023.6.1
leather                   0.3.4
Logbook                   1.5.3
lxml                      4.9.3
markdown-it-py            3.0.0
MarkupSafe                2.1.3
mashumaro                 3.6
mdurl                     0.1.2
minimal-snowplow-tracker  0.0.2
msgpack                   1.0.5
networkx                  2.8.8
packaging                 23.1
parsedatetime             2.4
pathspec                  0.11.1
pip                       22.0.3
pluggy                    1.2.0
protobuf                  4.23.4
psycopg2-binary           2.9.6
pycparser                 2.21
pydantic                  2.0.2
pydantic_core             2.1.2
Pygments                  2.15.1
pytest                    7.4.0
python-dateutil           2.8.2
python-slugify            8.0.1
pytimeparse               1.1.8
pytz                      2023.3
PyYAML                    6.0
redshift-connector        2.0.913
referencing               0.29.1
regex                     2023.6.3
requests                  2.31.0
rich                      13.4.2
rpds-py                   0.8.10
ruamel.yaml               0.17.32
ruamel.yaml.clib          0.2.7
s3transfer                0.6.1
scramp                    1.4.4
setuptools                68.0.0
six                       1.16.0
soupsieve                 2.4.1
sqlfluff                  2.1.2
sqlfluff-templater-dbt    2.1.2
sqlparse                  0.4.3
tblib                     2.0.0
text-unidecode            1.3
tqdm                      4.65.0
typing_extensions         4.7.1
urllib3                   1.26.16
Werkzeug                  2.3.6
wheel                     0.37.1
```

**Comment by alanmcruickshank** [comment]
@sziolko I'm still unable to recreate this issue. To help with debugging it, I've created a `Dockerfile` which should in theory recreate your environment. So that we don't need access to your project I've used the test dbt project included in the sqlfluff repo for testing.

```dockerfile
FROM python:3.9.17-slim
RUN apt-get update
RUN apt-get install git -y
RUN git clone https://github.com/sqlfluff/sqlfluff.git

WORKDIR sqlfluff
RUN pip install dbt-postgres==1.5.2 dbt-core==1.5.2
# Reset to tag at release from issue.
RUN git reset --hard 2.1.2
RUN pip install -e .
RUN pip install -e plugins/sqlfluff-templater-dbt/.

WORKDIR plugins/sqlfluff-templater-dbt/test/fixtures/dbt
RUN mkdir /root/.dbt
# Put profiles.yml file in the right place for newer versions (2.2.1+)
RUN cp profiles_yml/profiles.yml /root/.dbt/profiles.yml
# Put profiles.yml file in the right place for older versions (bug in .sqlfluff file)
RUN cp profiles_yml/profiles.yml ./profiles.yml
# NOTE: Make sure to have a postgres container running on localhost by default.
RUN dbt debug --project-dir dbt_project
RUN dbt deps --project-dir dbt_project
RUN sqlfluff lint dbt_project -p 4
```

This uses the same container, same python version, same dbt versions and same sqlfluff versions as your most recent post and while it comes up with some linting errors (mostly related to the test cases), I don't see the error which you've mentioned. Are you able to create a similar dockerfile which does recreate the issue you're seeing?

btw - if anyone else is experiencing the same issue and able to recreate it in a dockerfile, that would be very helpful in pinning down this issue.

**Comment by alanmcruickshank** [comment]
I think I know what's going on here, and why I couldn't recreate it. The `fork` pickler is only the default on pure linux platforms (see https://docs.python.org/3/library/multiprocessing.html#contexts-and-start-methods), and so on my system the forking pickler was never used.

For python 3.13 onward, the `fork` method has been deprecated, and with #6332 we've also explicitly set the process method to `spawn` for all platforms, which should have taken effect from SQLFluff 3.2.4 onward.

I'm going to close this issue as resolved, but if you're able to recreate the issue again using the most recent release then feel free to reopen this issue.
