### ISSUE TITLE
ALTER WAREHOUSE Snowflaken statements do no support variables or single quotes

### ISSUE THREAD

**Issue by Orangemic** [sqlfluff/sqlfluff#4937]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

Using the SQLParse Snowflake dialect, PRS errors are given on ALTER WAREHOUSE statements whereby either variables are used to describe the warehouse (e.g. IDENTIFIER($var)) or when using single quotes after a SET statement (e.g. SET WAREHOUSE_TYPE = 'STANDARD').

### Expected Behaviour

Using IDENTIFIER($var) and single quotes after a SET statement should not give PRS issues. 

### Observed Behaviour

Running this code gives PRS errors in SQLFluff using the Snowflake dialect, whereby the code is completed without errors in Snowflake itself:

`ALTER WAREHOUSE IDENTIFIER($var_wh) SET WAREHOUSE_TYPE = STANDARD;`

`ALTER WAREHOUSE WH_TEST SET SCALING_POLICY = 'ECONOMY';`

Running the code without the '_IDENTIFIER($var_wh)_' or single quotes around ECONOMY, gives no PRS issues:

`ALTER WAREHOUSE WH_TEST SET WAREHOUSE_TYPE = STANDARD;`

`ALTER WAREHOUSE WH_TEST SET SCALING_POLICY = ECONOMY;`

### How to reproduce

See [here a link](https://online.sqlfluff.com/fluffed?sql=H4sIAIo-nWQC_3P0CXENUgh3DHL18A8NdlUI94gPcQ0OUQh2DUGIxodEBrgq2CqoB4c4-rk4BrmoW_NyOaLp9HRx9QvxdPN0DdJQKUssii_P0ASbEuzs6OPp5x4f4O_j6RwJNMXV2d_P3zcSaAQACK0VRX0AAAA%3D&dialect=snowflake) to where the code breaks.

[In this example](https://online.sqlfluff.com/fluffed?sql=H4sIABpJnWQC_33LMQrAIAwF0L3QO-QepUPQTxWskSRFnLz_LerWreuDx8Wh1FmR5DFQT9NhTgb_dPpooJPMuUbWeOwb_zwLXHK9ZpOSw1gPQarcY7UXYXpbm28AAAA%3D&dialect=snowflake) the code would run without PRS errors.

### Dialect

I use the Snowflake dialect

### Version

> sqlfluff version 2.1.1
> Python version 3.10.12 

### Configuration

Honestly, our config is still pretty empty at this point:

[sqlfluff]
dialect = snowflake

### Are you willing to work on and submit a PR to address the issue?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by Orangemic** [comment]
I'm seeing that the ALTER WAREHOUSE statement uses  _Ref("NakedIdentifierSegment", optional=True)_ in the code.

```
match_grammar = Sequence(
        "ALTER",
        "WAREHOUSE",
        Sequence("IF", "EXISTS", optional=True),
        OneOf(
            Sequence(
                Ref("NakedIdentifierSegment", optional=True),
                OneOf(
                    "SUSPEND",
                    Sequence(
                        "RESUME",
                        Sequence("IF", "SUSPENDED", optional=True),
                    ),
                ),
            ),
```
            
However, I'm seeing that other ALTER STATEMENTS (e.g. alter storage integration) use _Ref("ObjectReferenceSegment")_ instead. Like the example here:

```
match_grammar = Sequence(
        "ALTER",
        Ref.keyword("STORAGE", optional=True),
        "INTEGRATION",
        Ref("IfExistsGrammar", optional=True),
        Ref("ObjectReferenceSegment"),
        OneOf(
            Sequence(
                "SET",
                OneOf(
                    Ref("TagEqualsSegment", optional=True),
                    AnySetOf(
                        Sequence(
                            "COMMENT", Ref("EqualsSegment"), Ref("QuotedLiteralSegment")
                        ),
```

Could it be the case that we need to use _ObjectReferenceSegment_ for ALTER WAREHOUSE statements instead of _NakedIdentifierSegment_?

**Comment by moreaupascal56** [comment]
Hi @Orangemic,

For the `ALTER WAREHOUSE WH_TEST SET SCALING_POLICY = 'ECONOMY';`, the issue is on the [WarehouseObjectPropertiesSegment](https://github.com/sqlfluff/sqlfluff/blob/eacd20ac144148ccce5db1b733bb220a2f80c812/src/sqlfluff/dialects/dialect_snowflake.py#L2826) where you see this: 
```
        Sequence(
            "SCALING_POLICY",
            Ref("EqualsSegment"),
            OneOf(
                "STANDARD",
                "ECONOMY",
            ),
        ),

```
There is no possibility for quotes. I think you can add the possibility quite easily, take inspiration from other places in the code :)

**Comment by moreaupascal56** [comment]
For the `ALTER WAREHOUSE IDENTIFIER($var_wh) SET WAREHOUSE_TYPE = STANDARD;`, I think your intuition is great, the issue is that indeed in all the possibilities given in the `AlterWarehouseStatementSegment` are always using the `NakedIdentifierSegment` for the warehouse "name". 

You can find `NakedIdentifierSegment` code [here](https://github.com/sqlfluff/sqlfluff/blob/eacd20ac144148ccce5db1b733bb220a2f80c812/src/sqlfluff/dialects/dialect_snowflake.py#L487) (and below):
```python
    NakedIdentifierSegment=SegmentGenerator(
        # Generate the anti template from the set of reserved keywords
        lambda dialect: RegexParser(
            # See https://docs.snowflake.com/en/sql-reference/identifiers-syntax.html
            r"[a-zA-Z_][a-zA-Z0-9_$]*",
            ansi.IdentifierSegment,
            type="naked_identifier",
            anti_template=r"^(" + r"|".join(dialect.sets("reserved_keywords")) + r")$",
        )
    ),
```

So there is no mention of any IDENTIFIER thing, I think [`ObjectReferenceSegment`](https://github.com/sqlfluff/sqlfluff/blob/eacd20ac144148ccce5db1b733bb220a2f80c812/src/sqlfluff/dialects/dialect_ansi.py#L967) (this is defined in `dialect_ansi.py`  because it is not overwritten in `dialect_snowflake.py`) will work, the key being the use of `SingleIdentifierGrammar` in `ObjectReferenceSegment` ! 


Have a try at it if you like and I can help if needed :) 
Have a great day !
