### ISSUE TITLE
SQLFluff at Coalesce 2020

### ISSUE THREAD

**Issue by alanmcruickshank** [sqlfluff/sqlfluff#518]
I've got a [slot at the online dbt conference](https://www.getdbt.com/coalesce/agenda/presenting-sqlfluff) in December to do a bit of a launch presentation for SQLFluff. I think it's important to:
a) raise the profile of the project and maybe get a few more users.
b) to start getting a bank of video content about sqlfluff out on the public internet (I think the talks are recorded).

I've attached the rough outline of what I'm planning on covering. I'd love some feedback from other @sqlfluff/sqlfluff-maintainers on whether I'm covering roughly the right stuff or whether there's anything else in particular that people think it's important to get across.

[SQLFluff @ Coalesce Online 2020 - Outline.pdf](https://github.com/sqlfluff/sqlfluff/files/5461966/SQLFluff.%40.Coalesce.Online.2020.-.Outline.pdf)

My ambition is that by the time the talk airs, we've got 0.4.0 released, hopefully including some of the performance gains which I'm working on at the moment.

**Comment by aaronsteers** [comment]
I love this - I've taken a quick pass and I'll spend a little time reviewing. Also, I'm happy to talk through anything if in-person discussion/feedback is helpful. I've been coding SQL professionally since around 2004 - and for at least the last ten years, I've been wishing for and wanting someone to create something like SQLFluff. Emphasized with the release of Black, the rise of Python and "pythonic" development, and the most recent momentum of the DBT community really to make SQL a first-class language. It's high time that we treated it like a first class language, and invested in SQL style guides and auto-formatting.

**Comment by pwildenhain** [comment]
Looking forward to catching the recording of this talk (9am EST is a _little_ early for me!).

I think what you've got so far is really good stuff, especially plugs for how it's already being used.

Some things I would consider adding (dependent on how the next month goes)
- Figuring out tighter integration with `dbt` while keeping dependencies manageable
    - Maybe a brief highlight of common issues people experience when using `sqlfluff` with `dbt`, e.g the wonky formatting of the templated sql
- Allowing organizations to design their own custom rules, based on their needs (which might not be generalizable)
- I would also mention that, since this is still in the experimental phase, more bug reports/feature requests are extremely helpful (not just people who can contribute to the codebase)

**Comment by pwildenhain** [comment]
Great work alan! 🎉
