### ISSUE TITLE
Two addtl repos to fold into the new org?

### ISSUE THREAD

**Issue by nolanbconaway** [sqlfluff/sqlfluff#523]
Less of an issue, more of a discussion topic!

I did a [github search](https://github.com/search?q=sqlfluff) to see what kinds of projects are using sqlfluff, and it turned up two additional paths to including sqlfluff in CICD

1. pre-commit (https://github.com/dmateusp/pre-commit-mirror-sqlfluff, https://github.com/badboy99tw/pre-commit-sqlfluff)
2. docker (https://github.com/wesley-dean-flexion/dockerized_sqlfluff)

Should any of these authors be invited to join the org?

**Comment by pwildenhain** [comment]
👍 For me!

**Comment by alanmcruickshank** [comment]
- Definitely up for the docker one.
- On the pre-commit ones, we should probably only bring in one. I would err toward the one by @dmateusp , because he's already involved with the project. 😄 

@nolanbconaway , feel like asking them?

**Comment by nolanbconaway** [comment]
I'm on it!

**Comment by dmateusp** [comment]
On the pre-commit, you'll see my repo copies https://github.com/pre-commit/mirrors-pylint, which automates the release process through a GitHub workflow that runs daily.
I think we could remove some things when bringing it over, since we'll want to release the pre-commit during the release process (we'll need to add the steps to the release process)

Also, I think we should merge https://github.com/sqlfluff/sqlfluff/pull/486 before bringing the pre-commit logic as the issue it aims to solve was quite a big UX issue for me

**Comment by nolanbconaway** [comment]
@dmateusp 👍 , it sounds like you've thought a little about this? I also think automating the release when we tag a new version is a good idea.

I've contacted the author of the docker repo, we will see if they're interested!

**Comment by nolanbconaway** [comment]
@alanmcruickshank , wesley-dean-flexion appears [interested](https://github.com/wesley-dean-flexion/dockerized_sqlfluff/issues/1) in folding the dockerized sqlfluff into this org! What are the next steps?

**Comment by dmateusp** [comment]
I'm actually focusing on https://github.com/sqlfluff/sqlfluff/pull/508 but I'm happy to draft a PR once that's done

**Comment by wesley-dean-flexion** [comment]
@nolanbconaway proposal about dockerization: I'll submit a PR with an updated `README.md` and the `Dockerfile`.  I recommend configuring the automated build process on Docker Hub so that users may pull `sqlfluff/sqlfluff:latest` (or whatever..) which would be (re-)built upon updates to a branch (typically `master`).

Also, it may be worthwhile to consider [applying for "Open Source status"](https://www.docker.com/blog/expanded-support-for-open-source-software-projects/) on Docker Hub to get around the pull rates; however, there have only been, to date, 107 pulls from the [registry](https://hub.docker.com/r/wesleydeanflexion/sqlfluff), so the rate limit most likely won't be an issue.

**Comment by wesley-dean-flexion** [comment]
For what it's worth, we use sqlfluff with a pre-commit hook on our analytics repos and it's worked extremely well.

(by "well," I'm speaking from the perspective of an ops person who doesn't like it when bad code makes it anywhere for which an alert would wake me in the middle of the night; the analysts, on the other hand, have a love/hate relationship with it)

**Comment by nolanbconaway** [comment]
> @nolanbconaway proposal about dockerization: I'll submit a PR with an updated `README.md` and the `Dockerfile`. I recommend configuring the automated build process on Docker Hub so that users may pull `sqlfluff/sqlfluff:latest` (or whatever..) which would be (re-)built upon updates to a branch (typically `master`).
> 
> Also, it may be worthwhile to consider [applying for "Open Source status"](https://www.docker.com/blog/expanded-support-for-open-source-software-projects/) on Docker Hub to get around the pull rates; however, there have only been, to date, 107 pulls from the [registry](https://hub.docker.com/r/wesleydeanflexion/sqlfluff), so the rate limit most likely won't be an issue.

Sounds good to me! Tho we should check with @alanmcruickshank about the automated build process, as linking builds to this repo has also been suggested elsewhere
