### ISSUE TITLE
Support GENERATE_DATE_ARRAY/GENERATE_TIMESTAMP_ARRAY in BigQuery

### ISSUE THREAD

**Issue by theianrobertson** [sqlfluff/sqlfluff#527]
Both of these calls to [GENERATE_DATE_ARRAY](https://cloud.google.com/bigquery/docs/reference/standard-sql/functions-and-operators#generate_date_array) throw a "Found unparsable section" when calling `sqlfluff lint file.sql --dialect bigquery`:

```sql
SELECT GENERATE_DATE_ARRAY(DATE '2010-01-01', DATE '2010-01-31') AS my_array;
```

```sql
SELECT GENERATE_DATE_ARRAY(DATE '2010-01-01', DATE '2010-01-31', INTERVAL '7' DAY) AS my_array;
```

[GENERATE_TIMESTAMP_ARRAY](https://cloud.google.com/bigquery/docs/reference/standard-sql/functions-and-operators#generate_timestamp_array) also does not parse:

```sql
SELECT GENERATE_TIMESTAMP_ARRAY(TIMESTAMP '2020-01-01', TIMESTAMP '2020-01-02', INTERVAL 1 HOUR) AS my_array
```

**Comment by barrywhart** [comment]
This issue is not specific to the two functions mentioned. BigQuery supports [Literal Coercion](https://cloud.google.com/bigquery/docs/reference/standard-sql/conversion_rules#literal_coercion), where string literals can be explicitly coerced to one of the following 4 types:
* `DATE`
* `DATETIME`
* `TIME`
* `TIMESTAMP`

This is a bit similar to Postgres `::` [casts](https://www.postgresql.org/docs/13/sql-expressions.html#SQL-SYNTAX-TYPE-CASTS), which is [already supported](https://github.com/sqlfluff/sqlfluff/blob/master/src/sqlfluff/core/dialects/dialect_ansi.py#L81).

Side note: The Postgres cast syntax is implemented in the core ANSI dialect. I wonder if we'd want to reconsider this in order to avoid having either:
* Two database-specific cast syntaxes both implemented in the ANSI dialect (messy?)
* Having one database-specific cast syntax implemented in the ANSI dialect and one in the BigQuery dialect (inconsistent ways of doing the same thing)

@theianrobertson: Would you mind changing the issue summary to mention Literal Coercion?
