### ISSUE TITLE
[TSQL] AL09 throws an AssertionError where assigning variables in a select statement

### ISSUE THREAD

**Issue by paysni** [sqlfluff/sqlfluff#5678]
### Search before asking

- [X] I searched the [issues](https://github.com/sqlfluff/sqlfluff/issues) and found no similar issues.

### What Happened

When having sqlfluff run fix on query where the variables are assigned in a select statement, AL09 will throw an error.

sqlfluff\rules\aliasing\AL09.py", line 99, in _eval
    assert whitespace and column_identifier and alias_identifier
AssertionError

### Expected Behaviour

It should be able to handle this valid sql statement.

### Observed Behaviour

It will throw an exception during the fix

sqlfluff\rules\aliasing\AL09.py", line 99, in _eval
    assert whitespace and column_identifier and alias_identifier
AssertionError

if I run lint it will give this error:
L:   4 | P:   1 | AL09 | Unexpected exception: ;
Could you open an issue at
                       | https://github.com/sqlfluff/sqlfluff/issues ?
You can
                       | ignore this exception for now, by adding '-- noqa: AL09'
                       | at the end
of line 4

                       | [aliasing.self_alias.column]

### How to reproduce

created simple query:
declare @variable nvarchar(50)

select @variable = Column1
from Table1
where Column2 = 'test'

and ran sqlfluff fix against that query.

### Dialect

tsql

### Version

3.0.1

### Configuration

[sqlfluff]
dialect = tsql
max_line_length = 120
 #RF06 Exclude forcing Quoted Identifier 
 #CV01 Exclude using != over <>
 #ST06 Exclude column reordering
exclude_rules = RF06, CV01, ST06
large_file_skip_byte_limit = 0
processes = -1

[sqlfluff:rules:layout.long_lines]
ignore_comment_lines = True
ignore_comment_clauses = True

[sqlfluff:layout:type:comma]
spacing_after = touch
line_position = leading

[sqlfluff:rules:capitalisation.identifiers]
ignore_words = dbo
#don't mess with Kronos tables that start with lower case t
ignore_words_regex = ^t[A-z][A-z]*$
extended_capitalisation_policy = pascal

[sqlfluff:indentation]
indent_joins = False
indent_unit = tab
indented_using_on = True
allow_implicit_indents = True
indented_on_contents = False

[sqlfluff:rules:references.special_chars]
ignore_words_regex = ([$(])

[sqlfluff:rules:capitalisation.types]
extended_capitalisation_policy = lower

[sqlfluff:rules:aliasing.table]
aliasing = explicit

[sqlfluff:rules:aliasing.column]
aliasing = explicit

[sqlfluff:rules:aliasing.length]
min_alias_length = 2

### Are you willing to work on and submit a PR to address the issue?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/sqlfluff/sqlfluff/blob/main/CODE_OF_CONDUCT.md)

**Comment by NickNIH** [comment]
FYI I'm seeing this with an even simpler example:
```sql
select @name1 = col1
from TableName
```
I'm also on 3.0.1 and dialect = tsql.

**Comment by drjwelch** [comment]
It's because of [this](https://github.com/sqlfluff/sqlfluff/blob/b813cc68ab4360b7e579a30cec7d65d680340c98/src/sqlfluff/dialects/dialect_tsql.py#L764) which understands that T-SQL allows you to write either

`SELECT my_column AS my_alias` [1] or

`SELECT my_alias = my_column` [2]

When you write a parameter assignment:

`SELECT @my_parameter = my_column` [3]

sqlfluff[tsql] sees this as an example of [2].

`@my_parameter=` matches for AltAliasExpressionSegment because this includes ParameterNameSegment as a possible such segment; but when it tries to obtain `alias_identifier` from this, it only looks for `naked_identifier` or `quoted_identifier` and ParameterNameSegment  is of type "parameter" so there are no matches and the resulting `alias_identifier` is None and fails the the assertion.

The solution I think is to redefine AltAliasExpressionSegment.  I will create a PR for this.
