### ISSUE TITLE
Do we need both the --force and --no-safety option in sqlfluff fix

### ISSUE THREAD

**Issue by pwildenhain** [sqlfluff/sqlfluff#578]
This seem like things that were developed iteratively, and from what I understand we might not need both of them? Or am I missing something?

**Comment by alanmcruickshank** [comment]
They have different functions, but they were developed separately, so it's likely that they might need a rethink in combination. Right now:

- `--no-safety` allows you to apply all rules without a rules filter. This would go away with #334.
- `--force` disables the user prompt when fixing so that there's no opportunity to review the fixes found before applying.

I think the intent would be that with #334, only the latter remains. Any other thoughts on improving this?

**Comment by pwildenhain** [comment]
I'm in favor of removing `--no-safety` and and applying all the rules by default, especially if we keep the `--force` flag

If others agree, I could tackle #334
