### ISSUE TITLE
Discussion: using a "parsing" library

### ISSUE THREAD

**Issue by dmateusp** [sqlfluff/sqlfluff#595]
@alanmcruickshank I see that the project implements its own parsing primitives from scratch in `parser/`, I'm curious if you think introducing a dedicated library like [parsy](https://parsy.readthedocs.io/en/latest/index.html) would be beneficial (I picked a parser combinator because it's close to the pattern we're using).

IMO that could mean less code to maintain on our end, and less concepts that people need to get "familiar with" if they want to contribute to the parser (and are familiar with parser combinators). I'd hope we would get performance improvements too!

**Comment by barrywhart** [comment]
This question arose in the context of PR #325. As it turns out, BigQuery UDF syntax cannot be parsed using the current parser. @alanmcruickshank made some experimental changes which didn't work, but with some additional tweaks, it _may_ work.

The particular challenge arose because BigQuery UDFs use angle brackets (`<`, `>`) to define composite types like structures and arrays. The parser cannot distinguish these from comparison operators, which use the same tokens.

See the discussion on that PR. In particular the parts about using a GLR parser, which can natively handle the kind of backtracking required in order to cleanly implement grammars with this sort of ambiguity.

**Comment by dmateusp** [comment]
@barrywhart thanks for the context! so I was waiting on some job to run, and I wrote this small snippet of code using `parsy` taking the example from the PR you linked:

```python
from parsy import *
from dataclasses import dataclass

@dataclass
class Keyword:
    raw: str

@dataclass
class Operator:
    raw: str

@dataclass
class Comparison:
    a: str
    operator: Operator
    b: str

keyword = regex(r"[0-9a-zA-Z_]+").map(Keyword)
operator = (string("<") | string(">")).map(Operator)

example_bq_type = "STRUCT<x INT64, y INT64>"
example_operator = "1 < 0"

@generate
def comparison():
    a = yield keyword
    yield whitespace
    _operator = yield operator
    yield whitespace
    b = yield keyword
    return Comparison(a=a, operator=_operator, b=b)

type_signature = seq(
    keyword, string("<"), keyword, whitespace, keyword, string(","),
    whitespace, keyword, whitespace, keyword, string(">")
)

print(type_signature.parse(example_bq_type))
# [Keyword(raw='STRUCT'), '<', Keyword(raw='x'), ' ', Keyword(raw='INT64'), ',', ' ', Keyword(raw='y'), ' ', Keyword(raw='INT64'), '>']

print(comparison.parse(example_operator))
# Comparison(a=Keyword(raw='1'), operator=Operator(raw='<'), b=Keyword(raw='0')

print((comparison | type_signature).parse(example_bq_type))
# [Keyword(raw='STRUCT'), '<', Keyword(raw='x'), ' ', Keyword(raw='INT64'), ',', ' ', Keyword(raw='y'), ' ', Keyword(raw='INT64'), '>']
```

Would you include `parsy` in your list of parsers ? :D I'm just a big fan of parser combinators over generators. I'd be happy to help on creating a POC or rewriting parts of our parsing logic

**Comment by alanmcruickshank** [comment]
In principle I'm very supportive of using an external parser, like you say, it's a lot less code to maintain, and it makes contribution easier.

My requirements list would be:
- Explicit whitespace parsing (for probably obvious reasons).
- A way of mapping the position in the parsed tree to the position in the original file (so we can apply fixes).
- Some level of recursion, so if multiple parts of the file are unparsable, that we return as many as possible to the user without just failing on the first. The more specific we can be on the exact problem the better - but I think the bar is pretty low here at the moment 🤷 .
- Ideally the ability to extend it so that if a section of the file was in a templated section in the original, that we can somehow represent that in the parsed structure, this means potential linting rules where we want to know if it was templated or not will still work.
- It should be modular, so that with multiple dialects we don't end up redefining the same constants in each dialect but just overwrite the elements that we need.

@dmateusp if you're happy to put together a POC that would be awesome! I realize this will be a pretty hefty change, so you may need several of us to help transition the dialects over to any new format that we move to.

**Comment by barrywhart** [comment]
@dmateusp: Your example looks promising. Are we sure it'll handle complex, real-world SQL that may mix both usages, etc., etc.

I don't have a strong position on the technology we use, just the requirement that it handle this tricky parsing situation.

I'd be happy to help if further evaluation is required, or with transitioning to whatever we choose. 💯💯

**Comment by dmateusp** [comment]
So I will take your requirements list @alanmcruickshank and your concerns @barrywhart and try to implement a POC that satisfies both, or at least illustrates what's not working!

We (at Earnest) use a parsing library often which follows the same principles as `parsy` (but in Haskell) to validate CLI inputs, the most complex use of it we have (that I'm aware of) is translating Glue API responses into types to do a translation from a Glue Schema to a Snowflake Schema. 

For these use cases in my opinion we end up with very readable and re-usable code, but I haven't done anything as complex as what is done in `sqlfluff`, so it'll be interesting!

**Comment by barrywhart** [comment]
@dmateusp and I had a brief discussion on this topic in the context of #325, which surfaced a tricky parsing ambiguity with angle brackets and relational operators. I think we are converging on a conclusion that we have a workable approach for now, so using a parsing library is not needed, at least for the foreseeable future. Should we close this ticket?

**Comment by alanmcruickshank** [comment]
Based on the lack of activity on this issue I'm going to close it for now. We can always re-open it at a later date if we need to.
