### ISSUE TITLE
"sqlfluff fix" loses comments in an IF()

### ISSUE THREAD

**Issue by barrywhart** [sqlfluff/sqlfluff#598]
This occurs with SQLFluff 0.4.0a1.

The following SQL, after fixing, loses the comment text:

```
  IF
    -- my comment
    (unsub_standing > open_standing
```

The result is:
```
        IF(unsub_standing > open_standing
```

**Comment by alanmcruickshank** [comment]
Great catch - I'd not thought of people putting comments in between function names and the brackets.

I'm tempted to catch this case a make it so no fix is generated because I'm not sure we could always reliably put the comment somewhere better. Do you have a better idea about how we should handle this?

**Comment by barrywhart** [comment]
I like the idea of treating parenthesized expressions similar to regular SQL constructs like SELECT, JOIN, etc. where things that don't fit on a line are split across lines. Is SQLFluff already doing something similar for some functions? (I'm thinking I've seen this happen somewhere -- I can track that down if it'd be helpful.)

Leaving it alone is also a viable option.

**Comment by barrywhart** [comment]
Oh, I just realized what you said -- it's interesting they put the comment *between* IF and (. I expected (and misread it) as:

IF(
    -- Comment

So I'm okay doing nothing or moving/combining the comment to *after* the (. Doing nothing is probably the right thing unless and until we find that this is a common pattern with users.
