### ISSUE TITLE
array_agg(x IGNORE NULLS) is unparseable - dialect bigquery

### ISSUE THREAD

**Issue by philipherrmann** [sqlfluff/sqlfluff#667]
With the following piece of test sql for BigQuery, one can produce an unparsable section error:
```
SELECT
    array_agg(t1) AS a1,
    array_agg(t2 IGNORE NULLS) AS a2,
FROM

    test_table

``` 
## Expected Behaviour

Expected test SQL to be parseable, as "IGNORE NULL" appears to be valid according to https://cloud.google.com/bigquery/docs/reference/standard-sql/aggregate_functions#array_agg and is understood from BQ.

## Observed Behaviour

== [test.sql] FAIL
L:   3 | P:   5 |  PRS | Found unparsable section: 'array_agg(t2 IGNORE
                       | NULLS)'

## Version
sqlfluff, version 0.3.6
Python 3.8.1

## Configuration
```
[sqlfluff]
dialect = bigquery
```

Given a bit of guidance, I could offer to commit and PR a fix, if nobody else wants to be super quick on this one.

**Comment by barrywhart** [comment]
Doing some reading about this... `IGNORE NULLS` and some related syntax is only applicable to the `ARRAY_AGG()` function. For a first implementation, I'm inclined to try and add it to the general expression syntax rather than adding a special  case for this one function. I believe this is similar in spirit to other pragmatic decisions we've made in order to limit the number of special cases we add, e.g. implement things in ANSI rather than dialects, avoiding having SQLFluff know about specific database functions, etc. Any thoughts?

**Comment by barrywhart** [comment]
Maybe add it to dialect_bigquery here?

```
bigquery_dialect.replace(
    FunctionContentsExpressionGrammar=OneOf(
        ...
```

**Comment by philipherrmann** [comment]
May be just the remark that I have used `IGNORE NULLS` successfully with a few other functions as well. At least it is valid BQ syntax for `FIST_VALUE` and `LAST_VALUE`, but apparently also for some other navigation functions (https://cloud.google.com/bigquery/docs/reference/standard-sql/navigation_functions).

**Comment by barrywhart** [comment]
Thanks, @philipherrmann, that is very helpful info!

I just created a PR for this issue: #727. Would you like to test it?
