### ISSUE TITLE
Look for project configuration in pyproject.toml.

### ISSUE THREAD

**Issue by shawnohare** [sqlfluff/sqlfluff#890]
A growing number of Python tools look for project-specific configuration in the `[tool.{app}]` section of the `pyproject.toml` file. It would be convenient if `sqlfluff` also inspected this section, especially for Python projects that use `poetry` as a build backend and thus do not rely on `setup.cfg` or potentially any of the other files currently inspected.

**Comment by alanmcruickshank** [comment]
@shawnohare this is a great idea. Do you know what the best practice precedence is between `pyproject.toml` and other files like `tox.ini` and `setup.cfg`? I'd love to make sure that SQLFluff is consistent with other tools in how it handles that.

**Comment by alanmcruickshank** [comment]
This would also be a great first issue for anyone new to the project if people want to have a go! (It might even be a one line change 😄 )

**Comment by alanmcruickshank** [comment]
The way to do this for anyone wanting to pick up this issue would be to add the filename in [load_config_at_path](https://github.com/sqlfluff/sqlfluff/blob/f4931633a6e398e198b14008e7092bf63760efee/src/sqlfluff/core/config.py#L239) and probably also extend [_get_config_elems_from_file](https://github.com/sqlfluff/sqlfluff/blob/f4931633a6e398e198b14008e7092bf63760efee/src/sqlfluff/core/config.py#L144) to use a proper toml parser if the extension of the file is `.toml` instead of the current `configparser` which is used for the other files.

**Comment by shawnohare** [comment]
> @shawnohare this is a great idea. Do you know what the best practice precedence is between `pyproject.toml` and other files like `tox.ini` and `setup.cfg`? I'd love to make sure that SQLFluff is consistent with other tools in how it handles that.

I honestly do not know if there’s necessarily a best practice around this. Here’s the order that `isort` uses: https://pycqa.github.io/isort/docs/configuration/config_files/ Personally I find this order to be pretty reasonable.

In my personal experience, many of the tools I’ve used which support `pyproject.toml` use this file exclusively unless they were created before this file became standard, in which case you get something like `isort`s preferences. Personally I’d prefer all tools moves toward deprecating everything but `pyrpoject.toml`, just for consistency, despite the fact that this file originally was for build related metadata.

**Comment by edgarrmondragon** [comment]
Hello all,

If nobody is working on this and there's interest in supporting `pyproject.toml` as a config source, I can work on a PR.

**Comment by barrywhart** [comment]
Sure, go for it!
