### ISSUE TITLE
Add parsing support for Postgres "EXPLAIN" statement

### ISSUE THREAD

**Issue by roblevy** [sqlfluff/sqlfluff#893]
The first example from the [Postgres EXPLAIN docs](https://www.postgresql.org/docs/12/sql-explain.html#examples) is:

```sql
EXPLAIN SELECT * FROM foo;
```

## Expected Behaviour

```python
>>> sqlfluff.parse("EXPLAIN SELECT * FROM foo;", dialect="postgres")
ParsedString(...)
```

## Observed Behaviour

```
SQLParseError: Found unparsable section: 'EXPLAIN SELECT * FROM foo'
```

## Steps to Reproduce

```python
import sqlfluff
sqlfluff.parse("EXPLAIN SELECT * FROM foo;", dialect="postgres")
```

## Version

sqlfluff: 0.4.1
Python: 3.8.6

## Configuration

No configuration file.

**Comment by alanmcruickshank** [comment]
@roblevy , thanks for the Issue report! We might have to implement this seperately for different dialects, each one seems to have a slightly different syntax. So that we cover your use case, which dialects are you most likely to use?

Docs for reference:
- mysql: https://dev.mysql.com/doc/refman/5.7/en/explain.html
- postgres: https://www.postgresql.org/docs/9.1/sql-explain.html
- snowflake https://docs.snowflake.com/en/sql-reference/sql/explain.html
- bigquery doesn't even support it 🤷  https://cloud.google.com/bigquery/query-plan-explanation

**Comment by roblevy** [comment]
Hi Alan,

Thanks for responding so quickly! We're using Postgres over here...

Thanks
Rob

**Comment by dmateusp** [comment]
@alanmcruickshank I ended up implementing the MySQL flavor as ANSI (it's the simplest case), and separately implemented a Snowflake and Postgres version, with Postgres being the most complicated (I actually had to spin up a Postgres on Docker to wrap my head around what's valid there)

https://github.com/sqlfluff/sqlfluff/pull/951
