### ISSUE TITLE
Add a config to L031 (avoid table aliases in from clauses and join conditions) for minimum length

### ISSUE THREAD

**Issue by fernandobrito** [sqlfluff/sqlfluff#974]
👋  This is our first week using sqlfluff in our organization and we are very excited! Thanks a lot for the project 🙌 .

In our dbt project, our team tends to use very long model names, for example: `app_open_session_15_minutes`, `audit_log_events_by_email`, `braze_campaign_analytics`, and we allow the use of aliases when joining models (for the tables above, some aliases that we could tolerate: `_session` (reserved word. bad example actually), `audit_log`,`campaign`).

We are having issues with the rule [L031](https://docs.sqlfluff.com/en/latest/rules.html#sqlfluff.core.rules.Rule_L031). We find it too strict. We had to disable it, but we still want to avoid aliases like `o` or `s`.

What do you think about introducing a new optional configuration for this rule to allow aliases that are longer than X characters? 

Or should that actually be a new rule? Like "Avoid short aliases in from clauses and join conditions.", and the default parameter could be something like `min_alias_length: 3`, so any alias >= 3 characters would be allowed.

**Comment by barrywhart** [comment]
This sounds reasonable to me. In our organization, we've been disabling this rule because it seemed too strict.

Somewhere in the backlog, I had created an issue about documenting the rationale for all the rules, especially for ones like this that may be a little more subjective.

Any thoughts, @sqlfluff/sqlfluff-maintainers?

**Comment by pwildenhain** [comment]
I really like this rule because you can read the sql and, if youre familiar with the database, know exactly which fields are being referenced. 

That being said we _also_ have very long table names that I wish we could alias sometimes.

What about a config for L031 called `acceptable_aliases` that houses a list of common aliases? So if you have a really long table name that you use repeatedly, you can stash it here. We could even make the config a dict rather than a list such that you say "this alias maps to this table" so that people can look them up of they want to familroze themselves with the project.

On @barrywhart's point I think we should definitely have at least a one-liner for each rule with a justification. Is there already and issue for that? This is something I would be up to tackle, it sounds fun and useful

**Comment by barrywhart** [comment]
#812 is the issue about documenting rationales.

**Comment by OTooleMichael** [comment]
Plus one for this issue also. In our DWH setup we have lots of exceptionally long schema & table names  (and need to reference everything by both table and schema) because we have lots of tables (and also a need to logically break those tables apart). `L031` make transform style queries too verbose for us and indeed because our tables are so long can sometimes mean the line length is too long as a result of the table name alone.

`min_alias_length: 3` seems like a great idea
but we could indeed use almost the opposite and benefit from a `max_alias_length`

Being able to enforce explicit would be really useful for us (as turning the rule off results in inconsistent or absent naming) and turning it on results in unreadable code :/ (for us)

**Comment by alanmcruickshank** [comment]
I think this is resolved with #3384
