### ISSUE TITLE
Failing to parse combination of comparison operators (BigQuery)

### ISSUE THREAD

**Issue by defonzie** [sqlfluff/sqlfluff#991]
## Expected Behaviour

No parsing errors for `SELECT 1 < 2, 2 > 1` with BigQuery dialect. Note that `SELECT 1 > 2, 2 < 1` works fine, so this seems to be an issue with the bracket/comparison operator distinction.

## Observed Behaviour

`Found unparsable section: ', 2 > 1'`

## Steps to Reproduce

http://sqlfluff-online.herokuapp.com/fluffed?sql=H4sIAG59gmAC_wt29XF1DlEwVLBRMNJRMFKwUzAEAPAOThMTAAAA&dialect=bigquery

## Version
0.5.2

## Configuration
```
dialect = bigquery
```

**Comment by barrywhart** [comment]
Agreed -- the angle bracket syntax in BigQuery `ARRAY` and `STRUCT` notation has challenged us several times. I'll take an initial look at this to see if it's an easy fix. If not, I may call on more expert help! @dmateusp @alanmcruickshank

**Comment by barrywhart** [comment]
@dmateusp or @alanmcruickshank: I ran through this example in the debugger a few times, specifically the `_bracket_sensitive_look_ahead_match` function. I'm struggling to understand why, for two similar queries, one parses and one doesn't.

Parses:
```
SELECT 1 < 2 and 2 > 1
```

Won't parse:
```
SELECT 1 < 2, 2 > 1
```

Since the first query parses and the second doesn't, my intuition is that the problem isn't confined to `_bracket_sensitive_look_ahead_match`, but in how other parts of the parser use it. Any insights?

**Comment by barrywhart** [comment]
After some more "grinding", I think a good solution may involve moving bracket pairs from a dialect-level value to a context-sensitive value. In other words, BigQuery angle brackets will only be allowed in the areas of the dialect that relate to function definition parameters and return types. This will require some dynamic bookkeeping in the parser, but should largely prevent future cases where comparison operators are misinterpreted as angle brackets.

I started down a dead end of doing this manually by explicitly changing the source code to annotate each affected segment in the dialect, but this is tedious, verbose, and will be hard to maintain.

I'll keep working along these lines unless someone objects or has other suggestions.

**Comment by barrywhart** [comment]
I found a pretty good solution, I think. #997
